# SPDX-FileCopyrightText: 2026 Alexandre 'kidev' Poumaroux
# SPDX-License-Identifier: Apache-2.0

"""Render the auth entity's two Source QML bridges.

With ``identity.provider_entity`` an auth entity owns ``identity`` (the OAuth engine) and
``sessions`` (the authoritative session store). Their Sources are the same in every project:
they forward each slot to the C++ engine the generated ``main.cpp`` puts in their context,
and forward answers back as signals. The text is fixed and checked in at
``tests/auth/auth/`` as that suite's fixture; a unit test keeps the two identical.
"""

from __future__ import annotations

_HEADER_QML = ("// SPDX-FileCopyrightText: 2026 Alexandre 'kidev' Poumaroux\n"
               "// SPDX-License-Identifier: Apache-2.0\n")


IDENTITY_SOURCE_QML = _HEADER_QML + """
import SynQt

// The authoritative identity Source on the auth entity, one instance per consuming edge.
// It bridges the connect point to the shared IdentityService (the `IdentityEngine` context
// object), which owns the client secret, the token exchange and the stored tokens. Results
// are emitted on this Source, so an identity reaches only the edge that asked. An answer
// that waits on the provider is delivered through this Source when it arrives.
//
// Generated by `synqt build` from `identity.provider_entity`. Edit the topology, not this
// file.
Identity {
    id: root

    function beginLogin(requestId, provider, redirectUri, binding, context) {
        const result = IdentityEngine.beginLogin(provider, redirectUri, binding, context);
        root.emitBeginResult(requestId, result.state, result.authorizeUrl, result.error);
    }

    // The browser binding of this login is stored with the state and checked here before
    // the code is spent, so any edge process can finish a login another began, and only
    // once.
    //
    // The engine answers asynchronously through this Source and the request id, so a slow
    // provider never blocks other callers.
    function exchangeCode(requestId, state, code, redirectUri, presentedBinding) {
        IdentityEngine.exchangeCode(state, code, redirectUri, presentedBinding,
                                    root, requestId);
    }

    function bindSession(state, sessionId) {
        IdentityEngine.bindSession(state, sessionId);
    }

    // A desktop claim is minted on the edge that answered the callback and redeemed over
    // the native client's own connection, possibly on another edge, so it is held here.
    // An empty sessionId means failure, whatever the cause.
    function holdClaim(code, sessionId, challenge) {
        IdentityEngine.holdClaim(code, sessionId, challenge);
    }

    function takeClaim(requestId, code, verifier) {
        root.emitClaimResult(requestId, IdentityEngine.takeClaim(code, verifier));
    }

    function releaseSession(sessionId) {
        IdentityEngine.releaseSession(sessionId);
    }
}
"""


SESSION_SOURCE_QML = _HEADER_QML + """
import SynQt

// The authoritative session Source on the auth entity, one instance per consuming edge.
// It bridges the connect point to the shared SessionManager (the `Sessions` context
// object): edge writes go into the store, and store changes go to every edge. A newly
// connected edge receives the current table.
//
// Generated by `synqt build` from `identity.provider_entity`. Edit the topology, not this
// file.
SessionStore {
    id: root

    function putSession(token, scope, identityJson, createdMs) {
        Sessions.applyUpsert(token, scope, identityJson, createdMs);
    }

    function removeSession(token) {
        Sessions.applyRemove(token);
    }

    // A session rotation on one edge, carried to every other, since the next page load
    // may land on any edge.
    function rotateSession(from, to) {
        Sessions.applyRotation(from, to);
    }

    function onUpserted(token, scope, identityJson, createdMs) {
        root.emitSessionUpserted(token, scope, identityJson, createdMs);
    }

    function onRemoved(token) {
        root.emitSessionRemoved(token);
    }

    function onRotated(from, to) {
        root.emitSessionRotated(from, to);
    }

    // `root` is the receiver, so the connections go when this Source does. An unshared
    // auth entity has one Source per edge, and an edge that reconnects gets a new one.
    Component.onCompleted: {
        Sessions.sessionUpserted.connect(root, onUpserted);
        Sessions.sessionRemoved.connect(root, onRemoved);
        Sessions.rotationRecorded.connect(root, onRotated);
        const rows = Sessions.snapshot();
        for (let i = 0; i < rows.length; ++i) {
            const row = rows[i];
            root.emitSessionUpserted(row.token, row.scope, row.identityJson, row.createdMs);
        }
    }
}
"""


# The Source file of each point, keyed by contract. Matches what `topologywriter` resolves
# for a point with no `server:`.
SOURCE_QML = {"Identity": IDENTITY_SOURCE_QML, "SessionStore": SESSION_SOURCE_QML}


def render_source_qml(contract: str) -> str:
    """The Source QML bridging one framework connect point to its C++ engine: the auth points
    here, the monitor points in :mod:`synqt.monitorentity`.
    """
    from . import monitorentity

    if contract in monitorentity.SOURCE_QML:
        return monitorentity.SOURCE_QML[contract]
    try:
        return SOURCE_QML[contract]
    except KeyError:
        raise KeyError(f"no generated Source QML for the contract {contract!r}") from None
