# SPDX-FileCopyrightText: 2026 Alexandre 'kidev' Poumaroux
# SPDX-License-Identifier: Apache-2.0

"""Render the app multi-binary build from the declared topology.

Two files: the project root ``CMakeLists.txt`` (four lines, written once) and
``generated/synqt.cmake`` (every target, rewritten on every build). Each entity is a target
linking its SynQt runtime library (``SynQtClient``, or the one
:func:`appmodel.service_libraries` names) and its contracts through ``synqt_add_contract``.
Services are inside ``if(NOT EMSCRIPTEN)``. Rendering is deterministic and needs no
compiler; compilation runs through the presets in :mod:`synqt.build`.
"""

from __future__ import annotations

import os
from pathlib import Path
from typing import Any, Dict, List, Optional

from . import appmodel, clientbuild, clientmodules, toolchain

_HEADER_CMAKE = ("# SPDX-FileCopyrightText: 2026 Alexandre 'kidev' Poumaroux\n"
                 "# SPDX-License-Identifier: Apache-2.0\n")


def render_project_cmakelists(config: Dict[str, Any]) -> str:
    """The project ``CMakeLists.txt``, at the root beside ``synqt.yaml``.

    Four lines that include the generated tree. The module must be declared from the root,
    because qmlcachegen names each compiled file after its path relative to that directory,
    and a ``..`` component (``app_../client``) is not a directory Windows can create.
    Written once and never overwritten, so targets added below the include survive.
    """
    name = str((config.get("project") or {}).get("name") or "app")
    return "\n".join([
        _HEADER_CMAKE,
        "",
        f"# {name}, built by SynQt.",
        "#",
        "# `synqt build` writes everything it generates into generated/, included below. This",
        "# file is yours: anything added after the include is kept.",
        "",
        "cmake_minimum_required(VERSION 3.21)",
        "",
        "# project() is here because CMake wants it directly in the top-level file. Edit it if",
        "# the build needs a language beyond C++.",
        f"project({name} LANGUAGES CXX)",
        "",
        'include("${CMAKE_CURRENT_LIST_DIR}/generated/synqt.cmake")',
    ]) + "\n"


def render_root_cmakelists(config: Dict[str, Any], synqt_root: os.PathLike[str] | str,
                           project_dir: os.PathLike[str] | str | None = None) -> str:
    """The multi-binary build for the whole topology, as ``generated/synqt.cmake``.

    Included by the root ``CMakeLists.txt`` (:func:`render_project_cmakelists`), so target
    paths are rooted at the project. Given `project_dir`, the client QML module gets every
    QML file in the client directory, not only the route views.
    """
    project = config.get("project", {})
    name = project.get("name", "app")
    qt_version = project.get("qt_version", toolchain.QT_VERSION)
    services = [e for e in appmodel.entities(config) if appmodel.is_service(e)]

    lines: List[str] = [_HEADER_CMAKE, "",
                        "# Generated by `synqt build` into generated/. Do not edit: it is",
                        "# rewritten from synqt.yaml on every build. The sources it names are in",
                        "# the entity folders one level up.",
                        "",
                        '# project() is in the root CMakeLists.txt that includes this,',
                        '# because CMake wants that call literal and in the top-level file.',
                        'set(CMAKE_RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}")', "",
                        "# This directory (<project>/generated) and the project root above it.",
                        "# Taken from CMAKE_CURRENT_LIST_DIR, since the root CMakeLists includes",
                        "# this file.",
                        'set(SYNQT_GENERATED "${CMAKE_CURRENT_LIST_DIR}")',
                        'get_filename_component(SYNQT_APP_ROOT "${SYNQT_GENERATED}/.."',
                        "                       ABSOLUTE)", "",
                        "# The SynQt framework sources (src/ runtime libraries, cmake/ helpers).",
                        "# Set at scaffold time; override with -DSYNQT_ROOT=... to use another",
                        "# checkout.",
                        f'set(SYNQT_ROOT "{Path(synqt_root).as_posix()}" '
                        'CACHE PATH "SynQt framework source root")',
                        "# The language version, the warnings that fail the build, and what",
                        "# release strips: the same settings the framework uses.",
                        'include("${SYNQT_ROOT}/cmake/SynQtBuildFlags.cmake")',
                        'include("${SYNQT_ROOT}/cmake/SynQtContracts.cmake")', "",
                        f"find_package(Qt6 {qt_version} REQUIRED COMPONENTS "
                        "Core Gui Qml Quick QuickControls2 Network RemoteObjects WebSockets)",
                        "qt_standard_project_setup(REQUIRES 6.12)", ""]

    clients = [entity for entity in appmodel.entities(config)
               if appmodel.is_client(entity)]
    if clients:
        root = Path(project_dir) if project_dir is not None else None
        # Once, however many clients: CMake refuses one source directory added twice.
        lines += ["# The client runtime, shared by every client entity below.",
                  'add_subdirectory("${SYNQT_ROOT}/src/client"'
                  ' "${CMAKE_BINARY_DIR}/SynQtClient")',
                  'set(SYNQT_EDGE_URL "wss://127.0.0.1:8443/sync" CACHE STRING '
                  '"Desktop client edge URL")', ""]
        for entity in clients:
            client_dir = (root / appmodel.entity_dir(entity)
                          if root is not None else None)
            lines += _client_cmake(config, entity,
                                   appmodel.qml_uri_for(config, entity), client_dir)

    if services:
        lines += ["", "# Service entities (host only; never built for WebAssembly)",
                  "if(NOT EMSCRIPTEN)",
                  f"    find_package(Qt6 {qt_version} REQUIRED COMPONENTS Sql)"]
        lines += _runtime_library_cmake(config, services)
        # A provider entity also links the provider library. SynQtService already links it
        # PUBLIC, so guard on the target.
        if any(appmodel.entity_type(e) in appmodel.TYPE_HELPERS or e.get("provider")
               for e in services):
            lines += ['    if(NOT TARGET SynQtProviders)',
                      '        add_subdirectory("${SYNQT_ROOT}/src/providers" '
                      '"${CMAKE_BINARY_DIR}/SynQtProviders")',
                      '    endif()']
        for entity in services:
            lines += _service_cmake(config, entity)
        lines.append("endif()")

    lines += _tests_cmake(config, qt_version,
                          Path(project_dir) if project_dir is not None else None)

    return "\n".join(lines) + "\n"


def _runtime_library_cmake(config: Dict[str, Any],
                           services: List[Dict[str, Any]]) -> List[str]:
    """Add only the SynQt runtime libraries this topology needs.

    Qt HTTP Server and Qt Network Authorization are GPLv3-only, so a project without a web
    edge or auth entity must not require them. Each directory guards its dependencies with
    `if(NOT TARGET ...)`.
    """
    needed = {library for entity in services
              for library in appmodel.service_libraries(config, entity)}
    lines: List[str] = []
    for library in ("SynQtService", "SynQtIdentity", "SynQtEdge", "SynQtGateway",
                    "SynQtMonitor"):
        if library not in needed:
            continue
        folder = appmodel.SERVICE_LIBRARIES[library]
        lines += [f"    if(NOT TARGET {library})",
                  f'        add_subdirectory("${{SYNQT_ROOT}}/{folder}" '
                  f'"${{CMAKE_BINARY_DIR}}/{library}")',
                  "    endif()"]
    return lines


def _tests_cmake(config: Dict[str, Any], qt_version: str,
                 project_dir: Optional[Path]) -> List[str]:
    """Wire in the application test target, when it has tests.

    `enable_testing()` is unconditional, so `synqt test` can tell no tests from not
    configured. The target lives in its own directory because repc writes
    `moc_rep_<contract>_source.cpp` into the directory's binary dir, and services also
    generate every contract at role source.
    """
    lines = ["", "enable_testing()"]
    if not appmodel.test_qml_files(project_dir):
        return lines

    return lines + [
        "",
        "# The application tests: QML, run through the SynQt.Test harness. Host only: a test runs",
        "# where the entity runs.",
        "if(NOT EMSCRIPTEN)",
        f"    find_package(Qt6 {qt_version} REQUIRED COMPONENTS QuickTest)",
        # Its own directory under generated/, for the repc reason spelled out above.
        '    add_subdirectory("${SYNQT_GENERATED}/tests"'
        ' "${CMAKE_BINARY_DIR}/app-tests")',
        "endif()",
    ]


#: The application test executable `generated/tests/CMakeLists.txt` defines; `synqt test`
#: builds it by this name.
TESTS_TARGET = "app_tests"


def render_tests_cmakelists(config: Dict[str, Any]) -> str:
    """The generated `generated/tests/CMakeLists.txt` defining the app test target. Source-tree
    paths come from `SYNQT_APP_ROOT` in the parent scope.
    """
    contracts = appmodel.contract_paths(config)
    lines = [_HEADER_CMAKE, "",
             "# Generated by `synqt build`. Do not edit; it is rewritten from synqt.yaml.",
             "#",
             "# In its own directory so repc's per-directory output does not collide with the",
             "# service entities, which generate the same contracts at the same role.",
             "",
             "if(NOT TARGET SynQtTesting)",
             '    add_subdirectory("${SYNQT_ROOT}/src/testing" "${CMAKE_BINARY_DIR}/SynQtTesting")',
             "endif()",
             "",
             f"qt_add_executable({TESTS_TARGET} tests_main.cpp)"]
    # Every contract's Source half: any point may be under test.
    forwarding = appmodel.session_forwarding_contracts(config)
    for contract, relative in contracts.items():
        carries = " FORWARDS_SESSION" if contract in forwarding else ""
        lines.append(f"synqt_add_contract({TESTS_TARGET} ROLE source{carries} "
                     f'SYN "${{SYNQT_APP_ROOT}}/{relative}")')
    lines += [
        "",
        "# Qt Quick Test finds the tst_*.qml files by directory at run time, so a new test file",
        "# needs no rebuild.",
        f"target_compile_definitions({TESTS_TARGET} PRIVATE",
        '    QUICK_TEST_SOURCE_DIR="${SYNQT_APP_ROOT}/tests")',
        f"target_link_libraries({TESTS_TARGET} PRIVATE",
        "    SynQtTesting Qt6::Core Qt6::Gui Qt6::Qml Qt6::Quick Qt6::QuickTest",
        "    Qt6::RemoteObjects)",
        "",
        "# offscreen: tests draw nothing and must run in CI without a display.",
        f"add_test(NAME app-tests COMMAND {TESTS_TARGET} -platform offscreen)",
    ]
    return "\n".join(lines) + "\n"


def _client_cmake(config: Dict[str, Any], client: Dict[str, Any], uri: str,
                  client_dir: Optional[Path] = None) -> List[str]:
    name = client.get("name", "client")
    consumed = appmodel.consumed_by(config, name)
    contracts = appmodel.contracts_of(consumed)
    # The window, every route view, and every other client QML file, so views and their
    # components are in the resource system.
    views = appmodel.client_qml_files(config, client_dir, client)
    folder = appmodel.entity_dir(client)
    # From the mirror under generated/, whose root objects load (synqt.qmlrewrite). Each
    # file gets an explicit QT_RESOURCE_ALIAS, so its resource path is unchanged.
    qml_files = ['"${SYNQT_GENERATED}/%s/%s"' % (folder, view) for view in views]
    lines = [f"# Client '{name}' (browser WASM and native desktop, from one QML)"]
    # Each file by absolute path, aliased to its place in the entity directory, where
    # loadFromModule() and the route table (qrc:/qt/qml/<Uri>/<view>) look. `pragma Shared`
    # files are marked QT_QML_SINGLETON_TYPE.
    for view, qml_file in zip(views, qml_files):
        singleton = (client_dir is not None
                     and appmodel.declares_singleton(client_dir / view))
        properties = ("QT_QML_SINGLETON_TYPE TRUE " if singleton else "")
        lines.append("set_source_files_properties(%s\n"
                     "    PROPERTIES %sQT_RESOURCE_ALIAS %s)"
                     % (qml_file, properties, view))
    lines += [
             f'qt_add_executable({name} '
             f'"${{SYNQT_GENERATED}}/{folder}/main.cpp")',
             f"qt_add_qml_module({name}",
             f"    URI {uri}",
             "    VERSION 1.0",
             "    QML_FILES"]
    lines += ["        " + qml_file for qml_file in qml_files]
    lines.append(")")
    paths = appmodel.contract_paths(config)
    forwarding = appmodel.session_forwarding_contracts(config)
    for contract in contracts:
        carries = " FORWARDS_SESSION" if contract in forwarding else ""
        # A framework contract (the console's) ships with the runtime, so the compiler reads
        # it from the checkout.
        framework = appmodel.framework_contract_path(contract)
        source = (f"${{SYNQT_ROOT}}/{framework}" if framework
                  else f"${{SYNQT_APP_ROOT}}/{paths[contract]}")
        lines.append(f"synqt_add_contract({name} ROLE replica{carries} "
                     f'SYN "{source}")')
    lines += [f'target_compile_definitions({name} PRIVATE SYNQT_EDGE_URL="${{SYNQT_EDGE_URL}}")',
              f"target_link_libraries({name} PRIVATE",
              "    SynQtClient Qt6::Core Qt6::Gui Qt6::Qml Qt6::Quick Qt6::QuickControls2",
              "    Qt6::Network Qt6::RemoteObjects Qt6::WebSockets)"]
    # Modules the client QML imports beyond the base (clientmodules.py). The WebAssembly
    # build links a QML plugin only when its package was found.
    add_ons = clientmodules.for_client(client_dir, views)
    if add_ons:
        qt_version = config.get("project", {}).get("qt_version", toolchain.QT_VERSION)
        lines += [f"# Imported by this client's QML: {', '.join(a.uri for a in add_ons)}",
                  f"find_package(Qt6 {qt_version} REQUIRED COMPONENTS "
                  + " ".join(add_on.component for add_on in add_ons) + ")",
                  f"target_link_libraries({name} PRIVATE "
                  + " ".join(add_on.target for add_on in add_ons) + ")"]
    lines += ["if(EMSCRIPTEN)",
              "    # Read window.location through Embind and drop the eval-based Emscripten",
              "    # runtime, for the edge CSP (no 'unsafe-eval').",
              f'    target_link_options({name} PRIVATE "-lembind" "-sDYNAMIC_EXECUTION=0")']
    if clientbuild.client_asyncify(config):
        lines += [
            "    # build.client_asyncify: with asyncify the main thread suspends in",
            "    # processEvents(), so any browser event sweeps the posted events. -Os is",
            "    # Emscripten's recommendation for asyncify; the stack is raised from 4 KB",
            "    # because the suspend point sits under Qt's event dispatch.",
            f'    target_link_options({name} PRIVATE',
            '        "-sASYNCIFY" "-sASYNCIFY_STACK_SIZE=131072" "-Os")']
    lines += ["endif()"]
    lines += _macos_bundle_cmake(config, name)
    lines += _linux_rpath_cmake(name)
    return lines


def _linux_rpath_cmake(name: str) -> List[str]:
    """Let the Linux desktop client find the Qt that `--deploy` puts beside it.

    Adds `$ORIGIN/lib` to BUILD_RPATH, after the kit path CMake derives. BUILD_RPATH,
    because the binary is copied out of the build tree (build.py `_install_binary`) and
    never installed.
    """
    return ["if(UNIX AND NOT APPLE AND NOT EMSCRIPTEN)",
            f"    set_target_properties({name} PROPERTIES",
            '        BUILD_RPATH "$ORIGIN/lib")',
            "endif()"]


def _macos_bundle_cmake(config: Dict[str, Any], name: str) -> List[str]:
    """Make the macOS desktop client an .app bundle.

    `macdeployqt` accepts only an .app, and a bundle has the Info.plist that signing and
    notarization need. The bundle identifier is a CMake cache variable with a placeholder
    default, since docs/desktop.md leaves it to the deployment step.
    """
    project = config.get("project", {}) if isinstance(config.get("project"), dict) else {}
    app = project.get("name") or name
    version = str(project.get("version") or "0.1.0")
    return ["if(APPLE AND NOT IOS)",
            f'    set(SYNQT_BUNDLE_ID "com.example.{app}.{name}" CACHE STRING',
            '        "macOS bundle identifier for the desktop client")',
            f"    set_target_properties({name} PROPERTIES",
            "        MACOSX_BUNDLE TRUE",
            f'        MACOSX_BUNDLE_BUNDLE_NAME "{name}"',
            '        MACOSX_BUNDLE_GUI_IDENTIFIER "${SYNQT_BUNDLE_ID}"',
            f'        MACOSX_BUNDLE_BUNDLE_VERSION "{version}"',
            f'        MACOSX_BUNDLE_SHORT_VERSION_STRING "{version}")',
            "endif()"]


def _service_cmake(config: Dict[str, Any], entity: Dict[str, Any]) -> List[str]:
    name = entity.get("name")
    # Framework points are skipped on both sides; their contracts are compiled into the
    # runtime libraries.
    owned = appmodel.app_points(appmodel.owned_by(config, name))
    consumed = appmodel.app_points(appmodel.mesh_consumed(config, name))
    # SynQtService, SynQtIdentity or SynQtEdge. licenses.py reads the same call.
    libs = list(appmodel.service_libraries(config, entity))
    if appmodel.entity_type(entity) in appmodel.TYPE_HELPERS or entity.get("provider"):
        libs.append("SynQtProviders")
    folder = appmodel.entity_dir(entity)
    paths = appmodel.contract_paths(config)
    lines = ["", f"    qt_add_executable({name} "
             f'"${{SYNQT_GENERATED}}/{folder}/main.cpp")']
    # Session forwarding is decided by the topology; both sides read it here.
    forwarding = appmodel.session_forwarding_contracts(config)
    for role, points in (("source", owned), ("replica", consumed)):
        for contract in appmodel.contracts_of(points):
            carries = " FORWARDS_SESSION" if contract in forwarding else ""
            lines.append(f"    synqt_add_contract({name} ROLE {role}{carries} "
                         f'SYN "${{SYNQT_APP_ROOT}}/{paths[contract]}")')
    # Qt6::Gui for the edge (QGuiApplication). A service gets Gui only through SynQtContract
    # when it owns a point (QStandardItemModel).
    qt_modules = "Qt6::Core Qt6::Gui Qt6::Network Qt6::Qml" if appmodel.is_edge(entity) \
        else "Qt6::Core Qt6::Network Qt6::Qml"
    link = " ".join(libs)
    lines += [f"    target_link_libraries({name} PRIVATE",
              f"        {link} {qt_modules}",
              "        Qt6::RemoteObjects Qt6::WebSockets)"]
    lines += _custom_provider_cmake(entity, name)
    return lines


def _custom_provider_cmake(entity: Dict[str, Any], name: str) -> List[str]:
    """Compile `providers/custom/` into an entity that selects a `custom:` provider.

    A registration macro runs only if its file is linked. Globbed with CONFIGURE_DEPENDS, so
    a provider added by `synqt add provider` builds with no further step. Every file goes
    into every entity that selects a custom provider; each looks up only its configured
    name.
    """
    provider = entity.get("provider") or {}
    if not str(provider.get("name", "")).startswith("custom:"):
        return []
    variable = "SYNQT_CUSTOM_PROVIDERS_%s" % name.upper().replace("-", "_")
    return ["",
            "    # This entity selects a custom: provider, so its implementation is linked in.",
            f"    file(GLOB {variable} CONFIGURE_DEPENDS",
            '        "${SYNQT_APP_ROOT}/providers/custom/*.cpp")',
            f"    if({variable})",
            f"        target_sources({name} PRIVATE ${{{variable}}})",
            "    endif()"]
