# SPDX-FileCopyrightText: 2026 Alexandre 'kidev' Poumaroux
# SPDX-License-Identifier: Apache-2.0

"""Render the monitor entity's two Source QML bridges.

A monitor owns ``ingest`` (every service reports through it) and ``console`` (the operator
client reads it). Their Sources are the same in every project: they forward each slot to the
C++ engine the generated ``main.cpp`` provides and publish its answers. See
:mod:`synqt.authentity`.
"""

from __future__ import annotations

_HEADER_QML = ("// SPDX-FileCopyrightText: 2026 Alexandre 'kidev' Poumaroux\n"
               "// SPDX-License-Identifier: Apache-2.0\n")


INGEST_SOURCE_QML = _HEADER_QML + """
import SynQt

// The monitor's ingest Source: one instance per reporting entity, so `Caller.entity` is
// that entity. Each batch goes to the `Monitor` engine with the name the transport
// verified; the name inside the batch is never read, so no entity can report as another.
//
// Generated by `synqt build` from `monitoring.entity`. Edit the topology, not this file.
Ingest {
    id: root

    function publish(events) {
        Monitor.take(events, Caller.entity);
    }

    function heartbeat(entity, sentMs) {
        // The certificate name, not the name the entity states.
        Monitor.heartbeat(Caller.entity, sentMs);
    }
}
"""


CONSOLE_SOURCE_QML = _HEADER_QML + """
import SynQt

// The monitor's console Source: one instance per operator, each with their own filter.
// Everything it publishes comes from the `Monitor` engine, so nothing here depends on the
// system being watched.
//
// Generated by `synqt build` from `monitoring.entity`. Edit the topology, not this file.
Console {
    id: root

    // This operator's last query, so a new batch republishes their view.
    property string askedText: ""
    property string askedEntity: ""
    property string askedSeverity: "trace"
    property int askedLimit: 500
    property string followedTrace: ""

    function ask(text, entity, minimumSeverity, limit) {
        root.followedTrace = "";
        root.askedText = text;
        root.askedEntity = entity;
        root.askedSeverity = minimumSeverity;
        root.askedLimit = limit;
        root.refresh();
    }

    function follow(traceId) {
        if (traceId.length === 0) {
            root.emitRefused("That event is not part of a trace.");
            return;
        }
        root.followedTrace = traceId;
        root.refresh();
    }

    function refresh() {
        if (root.followedTrace.length > 0) {
            root.eventsRows = Monitor.follow(root.followedTrace);
        } else {
            root.eventsRows = Monitor.ask(root.askedText, root.askedEntity,
                                          root.askedSeverity, root.askedLimit);
        }
        root.entitiesRows = Monitor.entityRows();
    }

    received: Monitor.received
    stored: Monitor.stored
    dropped: Monitor.dropped

    Component.onCompleted: {
        Monitor.arrived.connect(root.refresh);
        root.refresh();
    }

    // Disconnect explicitly. `Monitor` is process-wide and this Source belongs to one
    // operator, so the connection would outlive `root` and raise a TypeError on every
    // later batch.
    Component.onDestruction: {
        Monitor.arrived.disconnect(root.refresh);
    }
}
"""


#: The Source file of each point, keyed by contract. Matches what `topologywriter` resolves
#: for a point with no `server:`.
SOURCE_QML = {"Ingest": INGEST_SOURCE_QML, "Console": CONSOLE_SOURCE_QML}


def render_source_qml(contract: str) -> str:
    """The Source QML bridging one monitor connect point to its C++ engine."""
    try:
        return SOURCE_QML[contract]
    except KeyError:
        raise KeyError(f"no generated Source QML for the contract {contract!r}") from None
