# SPDX-FileCopyrightText: 2026 Alexandre 'kidev' Poumaroux
# SPDX-License-Identifier: Apache-2.0

"""Lower a parsed :class:`SynFile` to the generated C++/rep artifacts.

Four outputs per contract file:

* the ``.rep`` (records to POD, prop to PROP READPUSH, model to MODEL with only its
  declared roles, signal to SIGNAL, slot to SLOT with the return type when present);
* the owner-side Source helper (the contract name in QML), whose ``set<Model>(rows)`` and
  ``<model>Rows`` keep only declared roles and drop undeclared row fields;
* the consumer facade an accessor exposes (``<Contract>Consumer``);
* the consumer-side Replica QML registration.
"""

from __future__ import annotations

from typing import List

from .model import Contract, Model, Signal, Slot, SynFile
from .types import base_of, bound_of, cpp_type, is_generic, measure, unit_of

SPDX_CPP = (
    "// SPDX-FileCopyrightText: 2026 Alexandre 'kidev' Poumaroux\n"
    "// SPDX-License-Identifier: Apache-2.0\n"
    "// Generated by synqtc from a .syn contract. Do not edit.\n"
)


#: The extra leading argument every slot takes on a contract a service consumes: the session
#: the calling entity acts for. The rep, the owner override and the consumer invoke share
#: it.
SESSION_PARAM = "QVariantMap synqtSession"
SESSION_ARG = "synqtSession"


def _cap(name: str) -> str:
    return name[:1].upper() + name[1:]


def _gate(member) -> List[str]:
    """The scopes that reach `member`, empty when everyone the point is hosted for does."""
    return list(getattr(member, "scope", None) or [])


def _gate_literal(scopes: List[str]) -> str:
    return "QStringList{" + ", ".join(f'QStringLiteral("{name}")' for name in scopes) + "}"


def _is_gated(contract: Contract) -> bool:
    return any(_gate(member) for member in contract.members)


def _gated_props(contract: Contract):
    return [prop for prop in contract.props if _gate(prop)]


def _slot_params(syn: SynFile, slot, records, path) -> str:
    """A slot's parameter list as it is declared, session first when there is one."""
    declared = [f"{cpp_type(p.type, records, path=path, line=p.line, col=p.col)} {p.name}"
                for p in slot.params]
    if syn.forwards_session:
        declared.insert(0, SESSION_PARAM)
    return ", ".join(declared)


def _slot_args(syn: SynFile, slot) -> str:
    """A slot's arguments as they are passed on, session first when there is one."""
    passed = [param.name for param in slot.params]
    if syn.forwards_session:
        passed.insert(0, SESSION_ARG)
    return ", ".join(passed)


def _param_list(params, record_names, path) -> str:
    return ", ".join(
        f"{cpp_type(param.type, record_names, path=path, line=param.line, col=param.col)} {param.name}"
        for param in params
    )


# Declared bounds (`string[64]`, `list[100]`, `var[4096]`) are enforced at the generated
# boundary. A value over its bound is refused with a warning, never truncated.

#: The QtCore header a contract type needs. repc copies single-line directives from the top
#: of a `.rep` into its header, and its own includes stop at qvariant.h.
TYPE_INCLUDES = {
    "date": "QDateTime",
    "list": "QVariantList",
    "string": "QString",
    "url": "QUrl",
    "var": "QVariant",
    "variant": "QVariant",
}


def _bound_guard(spelling: str, value: str, where: str, field: str,
                 refuse: List[str], indent: str) -> List[str]:
    """Refuse `value` when it is over the bound its type was written with.

    `value` is already of the C++ type. Text is measured in characters, a list in elements,
    a `var` in serialized bytes.
    """
    bound = bound_of(spelling)
    size = measure(spelling, value)
    if bound is None or size is None:
        return []
    unit = unit_of(spelling)
    # Prefixed, like every local the generated code declares beside a contract's own names.
    local = f"synqt{_cap(field)}Size"
    guard = [
        f"const qsizetype {local}{{{size}}};",
        f"if ({local} > {bound}) {{",
        f'    qWarning("%s: \'%s\' is declared %s and the value is %lld {unit}; '
        'refused",',
        f'             "{where}", "{field}", "{spelling}",'
        f" static_cast<long long>({local}));",
    ] + [f"    {line}" for line in refuse] + ["}"]
    return [indent + line for line in guard]


def _written_types(syn: SynFile) -> List[str]:
    """Every type spelling the file writes, in no particular order."""
    written: List[str] = []
    for record in syn.records:
        written += [field.type for field in record.fields]
    for contract in syn.contracts:
        written += [prop.type for prop in contract.props]
        for model in contract.models:
            written += [role.type for role in model.roles]
        for signal in contract.signals:
            written += [param.type for param in signal.params]
        for slot in contract.slots:
            written += [param.type for param in slot.params]
            if slot.return_type is not None:
                written.append(slot.return_type)
    return written


def _type_includes(syn: SynFile) -> List[str]:
    """The Qt headers this file's types need, as `.rep` directives, sorted."""
    needed = {TYPE_INCLUDES[base_of(written)] for written in _written_types(syn)
              if base_of(written) in TYPE_INCLUDES}
    if syn.forwards_session and any(contract.slots for contract in syn.contracts):
        needed.add("QVariantMap")
    return sorted(needed)


def _bounds_a_var(syn: SynFile) -> bool:
    """Does anything here bound a `var`, and so need the serialized-size helper?"""
    return any(is_generic(written) and bound_of(written) is not None
               for written in _written_types(syn))


# `import SynQt` re-exports QtQuick. The re-export is installed with the contract
# registration, so every host of the QML (entity main, test harness, embedder) gets it.
# Idempotent.
MODULE_IMPORTS_INCLUDE = """// Present when a runtime is linked. A contract-only target has no
// engine and skips the re-export; the call below is guarded the same way.
#if __has_include(<moduleimports.h>)
#  include <moduleimports.h>
#  define SYNQT_HAS_MODULE_IMPORTS 1
#endif"""

MODULE_IMPORTS_CALL = """#ifdef SYNQT_HAS_MODULE_IMPORTS
    // Registering a contract makes `import SynQt` bring QtQuick with it, so the QML
    // registered below needs no second import line.
    SynQt::registerModuleImports();
#endif"""

ACTING_FOR_SHIM = """// A slot names the Caller it answers for while it runs, so calls the
// owner makes to another entity carry the same person. That lives in the consumer runtime;
// a contract-only target does not link it and gets a no-op.
#if __has_include(<actingfor.h>)
#  include <actingfor.h>
using SynqtActingFor = SynQt::ActingFor;
namespace {
QVariantMap synqtActingForSession() { return SynQt::ActingFor::current(); }
} // namespace
#else
namespace {
struct SynqtActingFor
{
    explicit SynqtActingFor(QObject *) {}
    ~SynqtActingFor() = default;
};
QVariantMap synqtActingForSession() { return QVariantMap{}; }
} // namespace
#endif
"""
CALL_SPAN_SHIM = """// Every slot call crossing a link is timed and recorded, however it
// ends: refused by a scope gate or an argument bound, forwarded to the entity behind a
// front, or answered by the owner QML. The destructor closes the record, so every return
// is traced. It records the shape of the call, never its arguments. It lives in the
// service runtime; a contract-only target gets a span that does nothing.
#if __has_include(<callspan.h>)
#  include <callspan.h>
using SynqtCallSpan = SynQt::CallSpan;
#else
namespace {
class SynqtCallSpan
{
public:
    SynqtCallSpan(const char *, const char *, QObject *, int) {}
    ~SynqtCallSpan() {}
    void refuse(const char *) {}
    void fail(const char *) {}
};
} // namespace
#endif
"""


VARIANT_BYTES_HELPER = """namespace {
// The serialized size of a var, which is what `var[n]` bounds.
qsizetype synqtVariantBytes(const QVariant &value)
{
    QByteArray buffer;
    QDataStream stream{&buffer, QIODevice::WriteOnly};
    stream << value;
    return buffer.size();
}
} // namespace
"""


# rep


def emit_rep(syn: SynFile) -> str:
    records = syn.record_names
    path = f"{syn.stem}.syn"
    lines: List[str] = [SPDX_CPP.rstrip("\n"), ""]

    # repc copies these into its header ahead of the declarations that need them.
    includes = _type_includes(syn)
    if includes:
        lines += [f"#include <{header}>" for header in includes]
        lines.append("")

    for record in syn.records:
        fields = ", ".join(
            f"{cpp_type(f.type, records, path=path, line=f.line, col=f.col)} {f.name}"
            for f in record.fields
        )
        lines.append(f"POD {record.name}({fields})")
    if syn.records:
        lines.append("")

    for contract in syn.contracts:
        lines.append(f"class {contract.name}")
        lines.append("{")
        for member in contract.members:
            lines.append("    " + _lower_member(syn, member, records, path))
        lines.append("}")
        lines.append("")

    return "\n".join(lines).rstrip("\n") + "\n"


def _lower_member(syn: SynFile, member, records, path) -> str:
    if isinstance(member, Model):
        # repc roles are names; the Source helper enforces the declared types at publish.
        return f"MODEL {member.name}({', '.join(role.name for role in member.roles)})"
    if isinstance(member, Signal):
        return f"SIGNAL({member.name}({_param_list(member.params, records, path)}))"
    if isinstance(member, Slot):
        params = _slot_params(syn, member, records, path)
        if member.return_type is None:
            return f"SLOT(void {member.name}({params}))"
        ret = cpp_type(member.return_type, records, path=path, line=member.line, col=member.col)
        return f"SLOT({ret} {member.name}({params}))"
    # Prop: READPUSH is the SynQt default and is written explicitly for clarity.
    ctype = cpp_type(member.type, records, path=path, line=member.line, col=member.col)
    return f"PROP({ctype} {member.name} READPUSH)"


# source side


def _has_models(syn: SynFile) -> bool:
    return any(contract.models for contract in syn.contracts)


def emit_source_helper_header(syn: SynFile, lstem: str) -> str:
    # <lstem>_rep.h points at the repc header for this target's role (_source, _replica or
    # _merged).
    out: List[str] = [SPDX_CPP, "#pragma once", "",
                      f'#include "{lstem}_rep.h"', "",
                      "#include <QList>",
                      "#include <QObject>",
                      "#include <QPointer>",
                      "#include <QQmlListProperty>", ""]
    # SourceModel refuses consumer writes and needs QtGui, so it is included only for a
    # contract with a model.
    if _has_models(syn):
        out += ["#include <sourcemodel.h>", "#include <QVariantList>", ""]
    records = syn.record_names
    path = f"{syn.stem}.syn"
    for contract in syn.contracts:
        out.append(_source_helper_class(syn, contract, records, path))
        out.append("")
    # The typed Caller subclass needs the service runtime's caller.h; guarded so a rep-only
    # target compiles.
    caller_subclasses = [_caller_subclass(contract, records, path)
                         for contract in syn.contracts if contract.signals]
    if caller_subclasses:
        out += ["#if __has_include(<caller.h>)",
                "#  include <caller.h>", "", "#  include <QVariant>", ""]
        out += caller_subclasses
        out += ["#endif", ""]
    out.append(f"void synqtRegister{_cap(syn.stem)}Sources();")
    out.append("")
    return "\n".join(out)


def _caller_subclass(contract: Contract, records, path) -> str:
    # A per-contract Caller with emit<Signal>(...) methods forwarding to emitSignal, for
    # Caller.emit<Signal>(...) in owner QML. The per-connection Source has one consumer, so
    # the signal reaches that caller only.
    name = contract.name
    lines = [
        f"// Typed Caller for {name}: Caller.emit<Signal>(...) sugar over emitSignal.",
        f"class {name}Caller : public SynQt::Caller",
        "{",
        "    Q_OBJECT",
        "",
        "public:",
        f"    explicit {name}Caller(QObject *parent = nullptr) : SynQt::Caller{{parent}} {{}}",
        "",
    ]
    for signal in contract.signals:
        params = _param_list(signal.params, records, path)
        variants = "".join(", QVariant::fromValue(%s)" % p.name for p in signal.params)
        lines.append(
            f"    Q_INVOKABLE void emit{_cap(signal.name)}({params})")
        lines.append(
            f'    {{ emitSignal(QStringLiteral("{signal.name}"){variants}); }}')
    lines.append("};")
    return "\n".join(lines)


def _source_helper_class(syn: SynFile, contract: Contract, records, path) -> str:
    name = contract.name
    lines = [
        "// Owner-side helper: the QML type the connect point's server file derives from,",
        f"// registered as \"{name}\" (the contract name; an entity never consumes a contract it",
        "// owns). Props and signals come from the generated Source. Publish a model by binding",
        "// <model>Rows to where the rows live, or by calling set<Model>(rows). Both keep only",
        "// the declared roles.",
        f"class {name}SourceHelper : public {name}SimpleSource",
        "{",
        "    Q_OBJECT",
        "    // A generated Source is not a visual item, so its default property is a QObject",
        "    // child list. The owner can declare non-visual children (a Timer, an Instantiator)",
        "    // inside it.",
        '    Q_CLASSINFO("DefaultProperty", "data")',
        "    Q_PROPERTY(QQmlListProperty<QObject> data READ data DESIGNABLE false)",
    ]
    if contract.models:
        # `<model>Rows` publishes a model declaratively: bind it to the rows and every
        # change republishes. Its name differs from the model's because the Source already
        # has `Q_PROPERTY(QAbstractItemModel *<model> ...)`, and QtRO finds that property by
        # name (qtro_property_index calls indexOfProperty).
        lines.append("")
        for model in contract.models:
            lines.append(f"    Q_PROPERTY(QVariantList {model.name}Rows READ {model.name}Rows")
            lines.append(f"               WRITE set{_cap(model.name)}Rows"
                         f" NOTIFY {model.name}RowsChanged)")
    lines += [
        "",
        "public:",
        f"    explicit {name}SourceHelper(QObject *parent = nullptr);",
        "",
        "    QQmlListProperty<QObject> data();",
        "",
        "    // Shared entities. A shared entity answers everyone from one Source, and each",
        "    // caller reaches it through a mirror. The mirror republishes the shared props,",
        "    // models and signals and forwards every slot with its caller bound. The runtime",
        "    // calls both by name.",
        "    Q_INVOKABLE void synqtSetCaller(QObject *caller);",
        "    Q_INVOKABLE void synqtMirror(QObject *shared);",
        "",
    ]
    lines += [
        "    // Fronts. A web edge may own a point it does not implement and hand each caller to",
        "    // the entity serving their scope; `replica` is that entity. Everything it publishes",
        "    // is followed and every slot is forwarded back. The runtime calls this by name.",
        "    Q_INVOKABLE void synqtRelay(QObject *replica);",
        "",
    ]
    lines += [
            "    // Scope gates. A member written `<admin> ...` reaches only a caller with that",
            "    // scope. The member stays declared, so a Replica still matches by signature,",
            "    // but nothing about it is published or accepted without the scope. Gating is on",
            "    // by default, for mirrors and per-caller Sources. The runtime turns it off on",
            "    // the one Source a shared entity answers from.",
            "    Q_INVOKABLE void synqtHoldsSharedState();",
            "",
            "public Q_SLOTS:",
            "    // Republish every gated member after this caller's scope changed. Members now",
            "    // out of reach are withdrawn.",
            "    void synqtRegate();",
            "",
            "public:",
            "",
        ]
    # One slots block for everything a QMetaMethod connects to: the pull slots a front
    # follows with and the emit<Signal> methods a mirror or front relays into.
    # QObject::connect refuses a Q_INVOKABLE target.
    followed = contract.props + contract.models
    if followed or contract.signals:
        lines.append("public Q_SLOTS:")
    for member in followed:
        lines.append(f"    void synqtPull{_cap(member.name)}();")
    if followed and contract.signals:
        lines.append("")
    if contract.signals:
        lines.append("    // Deliver a contract signal to the acquiring consumer(s). On a")
        lines.append("    // one Source per caller the sole consumer is that caller, so")
        lines.append("    // Caller.emitSignal(\"<Signal>\", ...) routes here to answer one caller.")
        for signal in contract.signals:
            params = _param_list(signal.params, records, path)
            lines.append(f"    void emit{_cap(signal.name)}({params});")
    if followed or contract.signals:
        lines += ["", "public:", ""]
    if contract.models:
        # repc declares a virtual set<Model>(QAbstractItemModel *) the owner must not call.
        # The `using` keeps it visible so it is not hidden (and warned about).
        for model in contract.models:
            lines.append(f"    using {name}SimpleSource::set{_cap(model.name)};")
        for model in contract.models:
            lines.append(
                f"    Q_INVOKABLE void set{_cap(model.name)}(const QVariantList &rows);")
        lines.append("")
        # The rows last published, read back by the bindable property. A QVariantList copy
        # is reference counted.
        for model in contract.models:
            lines.append(f"    QVariantList {model.name}Rows() const "
                         f"{{ return m_{model.name}Rows; }}")
            lines.append(f"    void set{_cap(model.name)}Rows(const QVariantList &rows) "
                         f"{{ set{_cap(model.name)}(rows); }}")
        lines.append("")
    bounded = _intercepted_props(contract)
    if bounded:
        lines.append("    // Bounded and gated props. repc makes every setter virtual, so both")
        lines.append("    // are kept here: an assignment that breaks a bound is refused and")
        lines.append("    // named, and one the caller has no scope for is remembered but not")
        lines.append("    // published, so what the Source pushes is always inside the contract")
        lines.append("    // and always something this caller may see.")
        for prop in bounded:
            ctype = cpp_type(prop.type, records, path=path, line=prop.line, col=prop.col)
            lines.append(f"    void set{_cap(prop.name)}({ctype} {prop.name}) override;")
        lines.append("")
    if contract.slots:
        lines.append("    // Consumer -> owner requests. Each dispatches to the owner's QML")
        lines.append("    // implementation (a QML function of the same name); a slot the owner")
        lines.append("    // did not implement is a no-op (or returns a default).")
        for slot in contract.slots:
            lines.append("    " + _slot_signature(syn, slot, records, path) + " override;")
        lines.append("")

    if contract.models:
        lines.append("Q_SIGNALS:")
        for model in contract.models:
            lines.append(f"    void {model.name}RowsChanged();")
        lines.append("")
    lines.append("private:")
    lines.append("    static void appendData(QQmlListProperty<QObject> *list, QObject *object);")
    lines.append("    // Make the shared Source's Caller be whoever is calling right now.")
    lines.append("    void synqtAdoptCaller(QObject *caller);")
    if _is_gated(contract):
        lines.append("    // Does the caller this Source answers hold any of these scopes?")
        lines.append("    // False when there is no caller at all, so a gate fails closed.")
        lines.append("    bool synqtAllows(const QStringList &scopes) const;")
    lines.append("")
    lines.append("    QList<QObject *> m_data;")
    lines.append("    QPointer<QObject> m_synqtCaller;")
    lines.append(f"    QPointer<{name}SourceHelper> m_synqtShared;")
    lines.append("    // The entity behind a front, when this Source is one caller's view of it.")
    lines.append("    QPointer<QObject> m_synqtRelay;")
    if contract.slots:
        lines.append("    bool m_synqtRelayTakesSession{false};")
    lines.append("    bool m_synqtUngated{false};")
    for prop in _gated_props(contract):
        ctype = cpp_type(prop.type, records, path=path, line=prop.line, col=prop.col)
        # What the owner last assigned, kept apart from what is published, so a gate can
        # publish it later or withdraw it.
        lines.append(f"    {ctype} m_synqt{_cap(prop.name)}{{}};")
    for model in contract.models:
        lines.append(f"    SynQt::SourceModel m_{model.name}Model;")
        lines.append(f"    QVariantList m_{model.name}Rows;")
    lines.append("};")
    return "\n".join(lines)


def _slot_signature(syn: SynFile, slot: Slot, records, path) -> str:
    params = _slot_params(syn, slot, records, path)
    if slot.return_type is None:
        return f"void {slot.name}({params})"
    ret = cpp_type(slot.return_type, records, path=path, line=slot.line, col=slot.col)
    return f"{ret} {slot.name}({params})"


SLOT_DISPATCH_HELPER = """namespace {
// Find the owner QML `function` implementing a slot: a method with the slot's name after
// the helper's own C++ methods (cppMethodCount). Returns its index, or -1 when the owner
// does not implement it, in which case the slot returns a default.
int synqtQmlSlotIndex(const QObject *object, const char *name, int paramCount,
                      int cppMethodCount)
{
    const QMetaObject *metaObject{object->metaObject()};
    for (int index{metaObject->methodCount() - 1}; index >= cppMethodCount; --index) {
        const QMetaMethod method{metaObject->method(index)};
        if (method.name() == name && method.parameterCount() == paramCount) {
            return index;
        }
    }
    return -1;
}

// Call the owner QML implementation at `index` with `arguments` converted to the declared
// parameter types, and return its answer as a QVariant. A typed QML function
// (`function walk(forward: real): void`) does not accept QVariant arguments, so each one is
// converted, and one that cannot be is refused, naming the parameter.
bool synqtInvokeQmlSlot(QObject *object, int index, QVariantList arguments,
                        QVariant *result)
{
    constexpr qsizetype mostArguments{10};
    const QMetaMethod method{object->metaObject()->method(index)};
    if (arguments.size() != method.parameterCount() || arguments.size() > mostArguments) {
        return false;
    }
    QGenericArgument passed[mostArguments]{};
    for (qsizetype at{0}; at < arguments.size(); ++at) {
        const QMetaType wanted{method.parameterMetaType(static_cast<int>(at))};
        QVariant &argument{arguments[at]};
        if (wanted == QMetaType::fromType<QVariant>()) {
            passed[at] = QGenericArgument("QVariant", &argument);
            continue;
        }
        if (!argument.convert(wanted)) {
            qWarning("%s: argument %d cannot be converted to %s, the type the owner declares",
                     method.methodSignature().constData(), static_cast<int>(at),
                     wanted.name());
            return false;
        }
        passed[at] = QGenericArgument(wanted.name(), argument.constData());
    }
    const QMetaType returned{method.returnMetaType()};
    QVariant answer{};
    QGenericReturnArgument into{};
    if (returned == QMetaType::fromType<QVariant>()) {
        into = QGenericReturnArgument("QVariant", &answer);
    } else if (returned.isValid() && returned.id() != QMetaType::Void) {
        answer = QVariant{returned};
        into = QGenericReturnArgument(returned.name(), answer.data());
    }
    const bool called{method.invoke(object, Qt::DirectConnection, into,
                                    passed[0], passed[1], passed[2], passed[3], passed[4],
                                    passed[5], passed[6], passed[7], passed[8], passed[9])};
    if (called && result) {
        *result = answer;
    }
    return called;
}
} // namespace
"""


RELAY_INTRO = """namespace {
// Wiring for a front: a web edge that owns a point it does not implement and hands each
// caller to the entity serving their scope. The browser acquires this helper, and a
// Replica of another contract answers it, so everything goes through the meta-object by
// name and needs no SynQt header. `synqt check` guarantees the entity behind a front
// carries exactly the members the front offers.
QMetaMethod synqtMethodNamed(const QMetaObject *metaObject, const char *name,
                             QMetaMethod::MethodType wanted)
{
    // Most derived first, so a Replica's own member wins.
    for (int index{metaObject->methodCount() - 1}; index >= 0; --index) {
        const QMetaMethod method{metaObject->method(index)};
        if (method.methodType() == wanted && method.name() == name) {
            return method;
        }
    }
    return QMetaMethod{};
}
"""

#: The same opening, for a file whose contracts raise no signal (no name lookup helper).
RELAY_INTRO_ONLY = RELAY_INTRO.split("QMetaMethod synqtMethodNamed")[0]

RELAY_FOLLOW_PROPERTY = """
// Follow `name` on `replica`: call `slot` on `source` now and whenever it changes.
bool synqtFollowProperty(QObject *replica, QObject *source, const char *name,
                         const char *slot)
{
    const int index{replica->metaObject()->indexOfProperty(name)};
    const int slotIndex{source->metaObject()->indexOfSlot(slot)};
    if (index < 0 || slotIndex < 0) {
        return false;
    }
    const QMetaProperty property{replica->metaObject()->property(index)};
    const QMetaMethod target{source->metaObject()->method(slotIndex)};
    if (property.hasNotifySignal()) {
        QObject::connect(replica, property.notifySignal(), source, target,
                         Qt::UniqueConnection);
    }
    target.invoke(source, Qt::DirectConnection);
    return true;
}
"""

RELAY_TAKES_SESSION = """
// Does the entity behind the front take the forwarded session on every call? A point a
// service consumes carries it as an extra first parameter, so one parameter more than
// the contract declares means yes.
bool synqtTakesSession(const QObject *replica, const char *name, int declared)
{
    const QMetaMethod method{synqtMethodNamed(replica->metaObject(), name,
                                              QMetaMethod::Slot)};
    return method.isValid() && method.parameterCount() == declared + 1;
}
"""

RELAY_FOLLOW_SIGNAL = """
// Relay a signal from the entity behind the front through the helper's own
// emit<Signal>, so it passes the same bound checks and scope gate.
bool synqtFollowSignal(QObject *replica, QObject *source, const char *name, const char *slot)
{
    const QMetaMethod signal{synqtMethodNamed(replica->metaObject(), name,
                                              QMetaMethod::Signal)};
    const QMetaMethod target{synqtMethodNamed(source->metaObject(), slot,
                                              QMetaMethod::Slot)};
    if (!signal.isValid() || !target.isValid()) {
        return false;
    }
    return static_cast<bool>(QObject::connect(replica, signal, source, target,
                                              Qt::UniqueConnection));
}
"""

RELAY_ROWS = """
// The rows a model replica holds, in the shape a Source publishes, read through the
// model's role names (the declared roles).
QVariantList synqtRowsOf(const QAbstractItemModel *model)
{
    QVariantList rows;
    if (!model) {
        return rows;
    }
    const QHash<int, QByteArray> names{model->roleNames()};
    const int count{model->rowCount()};
    rows.reserve(count);
    for (int row{0}; row < count; ++row) {
        const QModelIndex at{model->index(row, 0)};
        QVariantMap fields;
        for (auto role{names.constBegin()}; role != names.constEnd(); ++role) {
            fields.insert(QString::fromUtf8(role.value()), model->data(at, role.key()));
        }
        rows.append(fields);
    }
    return rows;
}

"""

RELAY_CLOSE = """} // namespace
"""


def emit_source_helper_source(syn: SynFile, lstem: str) -> str:
    out: List[str] = [SPDX_CPP,
                      f'#include "{lstem}_sourcehelper.h"', "",
                      "#include <QAbstractItemModel>",
                      "#include <QHash>",
                      "#include <QMetaMethod>",
                      "#include <QMetaProperty>",
                      "#include <QMetaType>",
                      "#include <QQmlEngine>",
                      "#include <QQmlListProperty>",
                      "#include <QVariant>",
                      "#include <QVariantList>",
                      "#include <QVariantMap>", ""]
    if _has_models(syn):
        out += ["#include <QStandardItem>", "",
                "#include <utility>", ""]
    if _bounds_a_var(syn):
        out += ["#include <QByteArray>",
                "#include <QDataStream>",
                "#include <QIODevice>", ""]
    # Present when a service runtime is linked. The registration below is guarded the same
    # way.
    out += ["#if __has_include(<sourcefactory.h>)",
            "#  include <sourcefactory.h>",
            "#endif", ""]
    out += [MODULE_IMPORTS_INCLUDE, ""]
    if any(contract.slots for contract in syn.contracts):
        out += [ACTING_FOR_SHIM, ""]
        out += [CALL_SPAN_SHIM, ""]
    if _bounds_a_var(syn):
        out += [VARIANT_BYTES_HELPER, ""]
    has_slots = any(contract.slots for contract in syn.contracts)
    if has_slots:
        out += [SLOT_DISPATCH_HELPER, ""]
    # Only the helpers this file's contracts call; an unused static function would fail the
    # warnings-as-errors build.
    follows = any(contract.props or contract.models for contract in syn.contracts)
    relays_signal = any(contract.signals for contract in syn.contracts)
    relays_slot = any(contract.slots for contract in syn.contracts)
    if follows or relays_signal or relays_slot:
        needs_lookup = relays_signal or relays_slot
        relay: List[str] = [RELAY_INTRO if needs_lookup else RELAY_INTRO_ONLY]
        if relays_slot:
            relay.append(RELAY_TAKES_SESSION)
        if follows:
            relay.append(RELAY_FOLLOW_PROPERTY)
        if relays_signal:
            relay.append(RELAY_FOLLOW_SIGNAL)
        if _has_models(syn):
            relay.append(RELAY_ROWS)
        relay.append(RELAY_CLOSE)
        out += ["".join(relay), ""]
    records = syn.record_names
    path = f"{syn.stem}.syn"
    for contract in syn.contracts:
        out.append(_source_helper_impl(syn, contract, records, path))
        out.append("")

    out.append(f"void synqtRegister{_cap(syn.stem)}Sources()")
    out.append("{")
    out.append(MODULE_IMPORTS_CALL)
    for contract in syn.contracts:
        out.append(
            f'    qmlRegisterType<{contract.name}SourceHelper>("SynQt", 1, 0, "{contract.name}");'
        )
    # Install the typed Caller factory when the service runtime is present, so
    # forUser/forEntity mint the <Contract>Caller.
    caller_contracts = [contract for contract in syn.contracts if contract.signals]
    if caller_contracts:
        out.append("#if __has_include(<caller.h>)")
        for contract in caller_contracts:
            out.append(
                f'    SynQt::Caller::registerCallerFactory(QStringLiteral("{contract.name}"),'
            )
            out.append(
                f"        [](QObject *parent) -> SynQt::Caller * "
                f"{{ return new {contract.name}Caller{{parent}}; }});"
            )
        out.append("#endif")
    # The mirror factory, on the same terms. A shared entity runtime builds one mirror per
    # caller and knows only the contract name.
    out.append("#if __has_include(<sourcefactory.h>)")
    for contract in syn.contracts:
        out.append(
            f'    SynQt::SourceFactory::registerSource(QStringLiteral("{contract.name}"),'
        )
        out.append(
            f"        [](QObject *parent) -> QObject * "
            f"{{ return new {contract.name}SourceHelper{{parent}}; }});"
        )
    out.append("#endif")
    out.append("}")
    out.append("")
    return "\n".join(out)


def _source_helper_impl(syn: SynFile, contract: Contract, records, path) -> str:
    name = contract.name
    lines: List[str] = []

    lines.append(f"{name}SourceHelper::{name}SourceHelper(QObject *parent)")
    lines.append(f"    : {name}SimpleSource{{parent}}")
    lines.append("{")
    for model in contract.models:
        # Publish an empty model from the constructor: enableRemoting() reads the model when
        # it registers the Source, and a null one is never replaced. The argument is spelled
        # out because `{}` would pick the QAbstractItemModel * overload.
        lines.append(f"    set{_cap(model.name)}(QVariantList{{}});")
    lines.append("}")
    lines.append("")

    # The default child list accepts non-visual QML children. The engine still completes
    # each one, so a child Timer with running: true starts.
    lines.append(f"QQmlListProperty<QObject> {name}SourceHelper::data()")
    lines.append("{")
    lines.append("    return QQmlListProperty<QObject>{this, nullptr,")
    lines.append(f"                                     &{name}SourceHelper::appendData,")
    lines.append("                                     nullptr, nullptr, nullptr};")
    lines.append("}")
    lines.append("")
    lines.append(f"void {name}SourceHelper::appendData(QQmlListProperty<QObject> *list,")
    lines.append("                                    QObject *object)")
    lines.append("{")
    lines.append("    if (!object) {")
    lines.append("        return;")
    lines.append("    }")
    lines.append(f"    {name}SourceHelper *self{{qobject_cast<{name}SourceHelper *>(list->object)}};")
    lines.append("    if (!self) {")
    lines.append("        return;")
    lines.append("    }")
    lines.append("    object->setParent(self);")
    lines.append("    self->m_data.append(object);")
    lines.append("}")
    lines.append("")

    lines.append(_mirror_impl(contract, records, path))
    lines.append("")

    lines.append(_relay_impl(contract, records, path))
    lines.append("")

    lines.append(_gate_impl(contract, records, path))
    lines.append("")

    for prop in _intercepted_props(contract):
        lines.append(_bounded_prop_impl(name, prop, records, path))
        lines.append("")

    for model in contract.models:
        lines.append(_set_model_impl(name, model, records, path))
        lines.append("")

    for slot in contract.slots:
        lines.append(_slot_impl(syn, name, slot, records, path))
    if contract.slots:
        lines.append("")

    for signal in contract.signals:
        lines.append(_emit_signal_impl(name, signal, records, path))
        lines.append("")

    return "\n".join(lines).rstrip("\n")


def _mirror_impl(contract: Contract, records, path) -> str:
    """The three methods that make one Source answerable to many callers.

    A shared entity keeps one Source and gives each caller a mirror. Pushes are copied out
    to every mirror; calls are forwarded back with the caller bound, so the shared Source's
    slots still see a Caller. A shared signal reaches every mirror; `Caller.emit<Signal>`
    reaches only the caller's own mirror.
    """
    name = contract.name
    helper = f"{name}SourceHelper"
    gated = _is_gated(contract)
    lines = [
        f"void {helper}::synqtSetCaller(QObject *caller)",
        "{",
        "    m_synqtCaller = caller;",
    ]
    if gated:
        lines += [
            "    if (caller) {",
            "        // Republish the gated members when this caller's scope changes. By name,",
            "        // like everything else on the Caller here. Unique, because a caller may be",
            "        // bound twice.",
            "        connect(caller, SIGNAL(scopeChanged()), this, SLOT(synqtRegate()),",
            "                Qt::UniqueConnection);",
            "    }",
            "    // Publish what the owner assigned before a caller was bound.",
            "    synqtRegate();",
        ]
    lines += [
        "}",
        "",
        f"void {helper}::synqtAdoptCaller(QObject *caller)",
        "{",
        "    // By name, so a target without the service runtime compiles. SynQt::Caller::adopt",
        "    // records this caller's identity and its mirror, so one shared Source can tell",
        "    // callers apart.",
        "    if (m_synqtCaller && caller && m_synqtCaller != caller) {",
        '        QMetaObject::invokeMethod(m_synqtCaller.data(), "adopt", Qt::DirectConnection,',
        "                                  Q_ARG(QObject *, caller));",
        "    }",
        "}",
        "",
        f"void {helper}::synqtMirror(QObject *shared)",
        "{",
        f"    {helper} *source{{qobject_cast<{helper} *>(shared)}};",
        "    if (!source || source == this) {",
        "        return;",
        "    }",
        "    m_synqtShared = source;",
    ]
    if contract.props:
        lines.append("")
        lines.append("    // Pushed state: taken as it stands, then followed.")
        for prop in contract.props:
            cap = _cap(prop.name)
            lines.append(f"    set{cap}(source->{prop.name}());")
            lines.append(f"    connect(source, &{name}Source::{prop.name}Changed, this,")
            lines.append(f"            &{name}SimpleSource::set{cap});")
    if contract.models:
        lines.append("")
        lines.append("    // Rows: republished from the shared Source's last publish, which")
        lines.append("    // already dropped everything the contract does not declare.")
        for model in contract.models:
            cap = _cap(model.name)
            lines.append(f"    set{cap}(source->{model.name}Rows());")
            lines.append(f"    connect(source, &{helper}::{model.name}RowsChanged, this,")
            lines.append(f"            [this, source]() {{ set{cap}(source->{model.name}Rows()); }});")
    if contract.signals:
        lines.append("")
        lines.append("    // A signal the shared Source raises is everyone's, so every mirror")
        lines.append("    // raises it too. One addressed to a single caller is emitted on that")
        lines.append("    // caller's mirror instead and never comes through here.")
        lines.append("    // Relayed into emit<Signal> rather than straight out, so a broadcast")
        lines.append("    // passes the same bound checks and the same scope gate as one sent")
        lines.append("    // to a single caller.")
        for signal in contract.signals:
            lines.append(f"    connect(source, &{name}Source::{signal.name}, this,")
            lines.append(f"            &{helper}::emit{_cap(signal.name)});")
    lines.append("}")
    return "\n".join(lines)


def _bounded_props(contract: Contract):
    """The contract's props that were written with a bound, in declaration order."""
    return [prop for prop in contract.props if bound_of(prop.type) is not None]


def _intercepted_props(contract: Contract):
    """The props whose setter the helper overrides: bounded, gated, or both. The bound is
    checked on the way in, the gate on the way out.
    """
    return [prop for prop in contract.props
            if bound_of(prop.type) is not None or _gate(prop)]


def _relay_impl(contract: Contract, records, path) -> str:
    """`synqtRelay`, and the pull slot behind each followed member.

    A front's Source publishes what the entity behind it holds and forwards calls there. A
    Replica is read-only, so following is one-way.
    """
    name = contract.name
    helper = f"{name}SourceHelper"
    lines = [
        f"void {helper}::synqtRelay(QObject *replica)",
        "{",
        "    if (m_synqtRelay && m_synqtRelay != replica) {",
        "        // Drop the previous target before following another. A front is re-pointed when",
        "        // the caller's scope moves to another tier, and when the mesh link returns with",
        "        // a new Replica.",
        "        QObject::disconnect(m_synqtRelay.data(), nullptr, this, nullptr);",
    ]
    for model in contract.models:
        lines += [
            "        if (QAbstractItemModel *rows{",
            f'                m_synqtRelay->property("{model.name}").value<QAbstractItemModel *>()}}) {{',
            "            QObject::disconnect(rows, nullptr, this, nullptr);",
            "        }",
        ]
    lines += [
        "    }",
        "    m_synqtRelay = replica;",
        "    if (!replica) {",
        "        return;",
        "    }",
    ]
    for prop in contract.props:
        lines.append(f'    synqtFollowProperty(replica, this, "{prop.name}",')
        lines.append(f'                        "synqtPull{_cap(prop.name)}()");')
    for model in contract.models:
        lines.append(f'    synqtFollowProperty(replica, this, "{model.name}",')
        lines.append(f'                        "synqtPull{_cap(model.name)}()");')
    for signal in contract.signals:
        lines.append(f'    synqtFollowSignal(replica, this, "{signal.name}",')
        lines.append(f'                      "emit{_cap(signal.name)}");')
    if contract.slots:
        first = contract.slots[0]
        lines.append("    // A contract carries the session on every slot or on none, so one")
        lines.append("    // answers for all of them.")
        lines.append(f'    m_synqtRelayTakesSession = synqtTakesSession(replica, "{first.name}",')
        lines.append(f"                                                {len(first.params)});")
    lines.append("}")

    for prop in contract.props:
        ctype = cpp_type(prop.type, records, path=path, line=prop.line, col=prop.col)
        lines += [
            "",
            f"void {helper}::synqtPull{_cap(prop.name)}()",
            "{",
            "    if (!m_synqtRelay) {",
            "        return;",
            "    }",
            f'    set{_cap(prop.name)}(qvariant_cast<{ctype}>(',
            f'        m_synqtRelay->property("{prop.name}")));',
            "}",
        ]
    for model in contract.models:
        cap = _cap(model.name)
        lines += [
            "",
            f"void {helper}::synqtPull{cap}()",
            "{",
            "    if (!m_synqtRelay) {",
            "        return;",
            "    }",
            "    QAbstractItemModel *rows{",
            f'        m_synqtRelay->property("{model.name}")'
            ".value<QAbstractItemModel *>()};",
            "    if (!rows) {",
            f"        set{cap}(QVariantList{{}});",
            "        return;",
            "    }",
            "    // The property changes once, when the Replica initializes; after that follow",
            "    // the model itself. Unique, because this runs on every change.",
        ]
        for signal in ("modelReset", "rowsInserted", "rowsRemoved", "rowsMoved",
                       "dataChanged", "layoutChanged"):
            lines += [
                f"    connect(rows, &QAbstractItemModel::{signal}, this,",
                f"            &{helper}::synqtPull{cap}, Qt::UniqueConnection);",
            ]
        lines += [
            f"    set{cap}(synqtRowsOf(rows));",
            "}",
        ]
    return "\n".join(lines)


def _gate_impl(contract: Contract, records, path) -> str:
    """The three methods behind a `<scope>` gate: ask, exempt, and publish again.

    `synqtAllows` calls SynQt::Caller::hasScope by name, so a target without the service
    runtime still compiles. It answers false when there is no caller. `synqtRegate` runs
    when the caller scope changes and republishes every gated member from the owner's last
    value: newly allowed members appear, newly denied ones are withdrawn.
    """
    name = contract.name
    helper = f"{name}SourceHelper"
    lines: List[str] = []
    if _is_gated(contract):
        lines += [
        f"bool {helper}::synqtAllows(const QStringList &scopes) const",
        "{",
        "    if (m_synqtUngated || scopes.isEmpty()) {",
        "        return true;",
        "    }",
        "    if (m_synqtCaller.isNull()) {",
        "        return false;",
        "    }",
        "    for (const QString &scope : scopes) {",
        "        bool granted{false};",
        '        QMetaObject::invokeMethod(m_synqtCaller.data(), "hasScope",',
        "                                  Qt::DirectConnection, Q_RETURN_ARG(bool, granted),",
        "                                  Q_ARG(QString, scope));",
        "        if (granted) {",
        "            return true;",
        "        }",
        "    }",
        "    return false;",
        "}",
        "",
        ]
    lines += [
        f"void {helper}::synqtHoldsSharedState()",
        "{",
        "    // The one Source a shared entity answers everyone from. It holds every value; the",
        "    // mirrors apply each caller's gate.",
        "    m_synqtUngated = true;",
        "    synqtRegate();",
        "}",
        "",
        f"void {helper}::synqtRegate()",
        "{",
    ]
    body: List[str] = []
    for prop in _gated_props(contract):
        # Through the setter, which is the one place the gate is written down.
        body.append(f"    set{_cap(prop.name)}(m_synqt{_cap(prop.name)});")
    for model in contract.models:
        if _gate(model):
            body.append(f"    set{_cap(model.name)}(m_{model.name}Rows);")
    if not body:
        # Only slots and signals are gated, and neither holds anything to republish.
        body.append("")
    lines += body
    lines.append("}")
    return "\n".join(lines)


def _bounded_prop_impl(class_name: str, prop, records, path) -> str:
    """The setter that keeps a bounded prop inside its bound. repc setters are virtual, so the
    override intercepts every assignment.
    """
    ctype = cpp_type(prop.type, records, path=path, line=prop.line, col=prop.col)
    helper = f"{class_name}SourceHelper"
    where = f"{class_name}.{prop.name}"
    lines = _bound_guard(prop.type, prop.name, where, prop.name, ["return;"], "    ")
    gate = _gate(prop)
    if gate:
        # Remembered even when not publishable. A closing gate restores the default on the
        # wire.
        lines += [
            f"    m_synqt{_cap(prop.name)} = {prop.name};",
            f"    if (!synqtAllows({_gate_literal(gate)})) {{",
            f"        {class_name}SimpleSource::set{_cap(prop.name)}({ctype}{{}});",
            "        return;",
            "    }",
        ]
    lines.append(f"    {class_name}SimpleSource::set{_cap(prop.name)}({prop.name});")
    body = "\n".join(lines)
    return f"void {helper}::set{_cap(prop.name)}({ctype} {prop.name})\n{{\n{body}\n}}"


def _emit_signal_impl(class_name: str, signal: Signal, records, path) -> str:
    params = _param_list(signal.params, records, path)
    args = ", ".join(p.name for p in signal.params)
    # A bound limits what crosses the link, so an owner signal is checked too.
    # Caller.emit<Signal>(...) comes through here as well.
    where = f"{class_name}.{signal.name}"
    lines: List[str] = []
    gate = _gate(signal)
    if gate:
        # Every way of raising this passes here, the shared broadcast included.
        lines += [
            f"    if (!synqtAllows({_gate_literal(gate)})) {{",
            "        return;",
            "    }",
        ]
    for param in signal.params:
        lines += _bound_guard(param.type, param.name, where, param.name, ["return;"], "    ")
    lines.append(f"    Q_EMIT {signal.name}({args});")
    body = "\n".join(lines)
    return "\n".join([
        f"void {class_name}SourceHelper::emit{_cap(signal.name)}({params})",
        "{",
        body,
        "}",
    ])


def _set_model_impl(class_name: str, model: Model, records, path) -> str:
    roles = model.roles
    role_array = ", ".join(f'QByteArrayLiteral("{role.name}")' for role in roles)
    lines = [
        f"void {class_name}SourceHelper::set{_cap(model.name)}(const QVariantList &rows)",
        "{",
        f"    static const QList<QByteArray> declaredRoles{{{role_array}}};",
        "    QHash<int, QByteArray> roleNames;",
        "    for (int roleIndex{0}; roleIndex < declaredRoles.size(); ++roleIndex) {",
        "        roleNames.insert(Qt::UserRole + roleIndex, declaredRoles.at(roleIndex));",
        "    }",
    ]
    gate = _gate(model)
    if gate:
        # Remembered before the gate, for synqtRegate. Denied, the model is emptied so
        # consumers lose the rows. It still names the declared roles: QtRO reads them once,
        # when the Source is remoted, and a gate that opens later cannot add one.
        lines += [
            f"    m_{model.name}Rows = rows;",
            f"    if (!synqtAllows({_gate_literal(gate)})) {{",
            f"        m_{model.name}Model.clear();",
            f"        m_{model.name}Model.setItemRoleNames(roleNames);",
            f"        {class_name}SimpleSource::set{_cap(model.name)}(&m_{model.name}Model);",
            f"        Q_EMIT {model.name}RowsChanged();",
            "        return;",
            "    }",
        ]
    lines += [
        "    // Built first and committed at the end, so a row that does not match the contract",
        "    // refuses the whole publish.",
        "    QList<QStandardItem *> items;",
        "    items.reserve(rows.size());",
        "    for (qsizetype rowIndex{0}; rowIndex < rows.size(); ++rowIndex) {",
        "        const QVariantMap row{rows.at(rowIndex).toMap()};",
        "        QStandardItem *item{new QStandardItem{}};",
        "        items.append(item);",
    ]
    for index, role in enumerate(roles):
        lines.append("")
        lines += _role_conversion(class_name, model, role, index, records, path)
    lines += [
        "    }",
        f"    m_{model.name}Model.clear();",
        f"    m_{model.name}Model.setItemRoleNames(roleNames);",
        "    for (QStandardItem *item : std::as_const(items)) {",
        f"        m_{model.name}Model.appendRow(item);",
        "    }",
        f"    {class_name}SimpleSource::set{_cap(model.name)}(&m_{model.name}Model);",
        # Recorded after the commit, so a refused publish leaves the property unchanged.
        f"    m_{model.name}Rows = rows;",
        f"    Q_EMIT {model.name}RowsChanged();",
        "}",
    ]
    return "\n".join(lines)


def _role_conversion(class_name: str, model: Model, role, index: int, records, path) -> List[str]:
    """The lines that copy one declared role from a row onto the item. Undeclared fields are
    never read. A `var` role is stored as is; others are converted, and a failed conversion
    refuses the publish.
    """
    key = f'QStringLiteral("{role.name}")'
    where = f"{class_name}.{model.name}"
    refuse = ["qDeleteAll(items);", "return;"]
    if is_generic(role.type):
        lines = [
            f"        // {role.name}: declared {role.type}, stored as it arrives.",
            f"        const QVariant {role.name}Value{{row.value({key})}};",
        ]
        lines += _bound_guard(role.type, f"{role.name}Value", where, role.name, refuse,
                              " " * 8)
        lines.append(f"        item->setData({role.name}Value, Qt::UserRole + {index});")
        return lines
    ctype = cpp_type(role.type, records, path=path, line=role.line, col=role.col)
    lines = [
        f"        // {role.name}: declared {role.type}.",
        f"        QVariant {role.name}Value{{row.value({key})}};",
        f"        if (!{role.name}Value.isValid()) {{",
        f"            {role.name}Value = QVariant{{QMetaType::fromType<{ctype}>()}};",
        "        } else {",
    ]
    lines += [
        f"            if (!{role.name}Value.convert(QMetaType::fromType<{ctype}>())) {{",
        '                qWarning("%s row %lld: role \'%s\' is declared %s and a %s does '
        'not "',
        '                         "convert to it; the publish is refused",',
        f'                         "{where}", static_cast<long long>(rowIndex),'
        f' "{role.name}", "{role.type}",',
        f"                         row.value({key}).typeName());",
        "                qDeleteAll(items);",
        "                return;",
        "            }",
    ]
    lines += _bound_guard(role.type, f"qvariant_cast<{ctype}>({role.name}Value)", where,
                          role.name, refuse, " " * 12)
    lines += [
        "        }",
        f"        item->setData({role.name}Value, Qt::UserRole + {index});",
    ]
    return lines


def _slot_impl(syn: SynFile, class_name: str, slot: Slot, records, path) -> str:
    helper = f"{class_name}SourceHelper"
    is_void = slot.return_type is None
    ret = "void" if is_void else cpp_type(
        slot.return_type, records, path=path, line=slot.line, col=slot.col)
    params = _slot_params(syn, slot, records, path)
    head = f"{ret} {helper}::{slot.name}({params})"

    # The owner implements the slot as a QML `function`. Arguments go over as QVariants that
    # synqtInvokeQmlSlot converts to the declared parameter types, and the result is
    # converted to the slot's C++ type.
    arguments = ("QVariantList{"
                 + ", ".join(f"QVariant::fromValue({p.name})" for p in slot.params) + "}")

    # Bounds are checked before the owner QML sees the call.
    where = f"{class_name}.{slot.name}"
    refuse = ["return;"] if is_void else [f"return {ret}{{}};"]

    lines: List[str] = []
    if syn.forwards_session:
        # Take the session the calling entity acts for first, so the checks below and the
        # span see the right Caller. Sent on every call, empty included, so a reused Caller
        # never keeps the previous session. A browser Caller ignores it
        # (SynQt::Caller::assumeSession).
        lines += [
            "    if (m_synqtCaller) {",
            '        QMetaObject::invokeMethod(m_synqtCaller.data(), "assumeSession",',
            "                                  Qt::DirectConnection,",
            f"                                  Q_ARG(QVariantMap, {SESSION_ARG}));",
            "    }",
        ]
    # Opened before any return and closed by its destructor, so every path is timed.
    lines += [
        f'    SynqtCallSpan synqtSpan{{"{class_name}", "{slot.name}",',
        f"                            m_synqtCaller.data(), {len(slot.params)}}};",
    ]
    gate = _gate(slot)
    if gate:
        # After the session is taken, so the scope is the one the call runs under. Refused
        # before the owner QML or any argument is reached.
        lines += [
            f"    if (!synqtAllows({_gate_literal(gate)})) {{",
            f'        qWarning("%s: refused, the caller does not hold the scope it needs",',
            f'                 "{where}");',
            '        synqtSpan.refuse("scope");',
        ] + [f"        {line}" for line in refuse] + ["    }"]
    # Each refusal names the check that made it.
    refuse_bound = ['synqtSpan.refuse("bound");'] + refuse
    for param in slot.params:
        lines += _bound_guard(param.type, param.name, where, param.name, refuse_bound, "    ")
    if getattr(slot, "capture", False):
        # Captured only where the contract asks, and only after the bounds have run.
        lines.append("    // `capture` on this member: the contract asked for the values.")
        for param in slot.params:
            lines.append(f'    synqtSpan.capture(QStringLiteral("{param.name}"),')
            lines.append(f"                      QVariant::fromValue({param.name}));")
    # The caller being answered, for as long as the slot runs, so onward calls carry it.
    lines.append(f"    const SynqtActingFor synqtActing{{m_synqtCaller.data()}};")
    # A front relays the call to the entity serving this caller's scope, with the session,
    # so that entity authorizes the person.
    session_arg = "Q_ARG(QVariantMap, synqtActingForSession())"
    relay_args = "".join(
        ",\n                                  Q_ARG(%s, %s)"
        % (cpp_type(param.type, records, path=path, line=param.line, col=param.col),
           param.name)
        for param in slot.params)
    plain_args = relay_args.lstrip(",\n ")
    lines += [
        "    if (m_synqtRelay) {",
        "        if (m_synqtRelayTakesSession) {",
        f'            QMetaObject::invokeMethod(m_synqtRelay.data(), "{slot.name}",',
        f"                                      {session_arg}{relay_args});",
        "        } else {",
        f'            QMetaObject::invokeMethod(m_synqtRelay.data(), "{slot.name}"'
        + (f",\n                                      {plain_args});" if slot.params else ");"),
        "        }",
    ] + [f"        {line}" for line in refuse] + ["    }"]
    # A mirror binds its caller and hands the call to the shared Source.
    forward = f"m_synqtShared->{slot.name}({_slot_args(syn, slot)})"
    lines += [
        "    if (m_synqtShared) {",
        "        m_synqtShared->synqtAdoptCaller(m_synqtCaller);",
        f"        {'return ' if not is_void else ''}{forward};",
    ]
    if is_void:
        lines.append("        return;")
    lines.append("    }")
    lines += [
        f'    const int synqtIndex{{synqtQmlSlotIndex(this, "{slot.name}", {len(slot.params)},',
        f"                                          {helper}::staticMetaObject.methodCount())}};",
    ]
    if is_void:
        lines += [
            "    if (synqtIndex >= 0) {",
            f"        synqtInvokeQmlSlot(this, synqtIndex, {arguments}, nullptr);",
            "    }",
        ]
    else:
        lines += [
            "    QVariant synqtResult{};",
            "    if (synqtIndex >= 0) {",
            f"        synqtInvokeQmlSlot(this, synqtIndex, {arguments}, &synqtResult);",
            "    }",
            f"    return qvariant_cast<{ret}>(synqtResult);",
        ]
    body = "\n".join(lines)
    return f"{head}\n{{\n{body}\n}}"


# Consumer side.
#
# The consumer facade is what an accessor (Server, Database, ...) exposes for a consumed
# connect point. It forwards the Replica props, models and signals, turns a returning slot
# into a Promise (`slot(args).then(...)`), and registers with the ConnectPointResolver for
# `<Contract>.on<Signal>` handlers. It reflects through the metaobject, so it serves typed
# and dynamic Replicas alike. Guarded on <consumerbase.h>.


def _types_csv(params, records, path) -> str:
    return ",".join(
        cpp_type(param.type, records, path=path, line=param.line, col=param.col)
        for param in params
    )


def _qarg_suffix(params, records, path) -> str:
    terms = [
        "Q_ARG(%s, %s)"
        % (cpp_type(param.type, records, path=path, line=param.line, col=param.col), param.name)
        for param in params
    ]
    return "".join(", " + term for term in terms)


def emit_consumer_header(syn: SynFile, lstem: str) -> str:
    out: List[str] = [SPDX_CPP, "#pragma once", ""]
    out += ["#if __has_include(<consumerbase.h>)",
            "#  include <consumerbase.h>",
            "#  include <promise.h>", "",
            f'#  include "{lstem}_rep.h"', "",
            "#  include <readonlymodel.h>", "",
            "#  include <QtQml/qqmlregistration.h>", "",
            "#  include <QAbstractItemModel>",
            "#  include <QList>",
            "#  include <QObject>",
            "#  include <QString>", ""]
    records = syn.record_names
    path = f"{syn.stem}.syn"
    for contract in syn.contracts:
        out.append(_consumer_class(contract, records, path))
        out.append("")
    out.append("#endif")
    out.append("")
    out.append(f"void synqtRegister{_cap(syn.stem)}Consumers();")
    out.append("")
    return "\n".join(out)


def _consumer_class(contract: Contract, records, path) -> str:
    name = contract.name
    lines = [
        f"// Consumer facade for {name}: what `{name}` is in the QML of an entity that consumes",
        f"// {name}'s point. It is the accessor and also the attached object for the QML type",
        f"// `{name}`, so `{name}.doThing()`, a binding on `{name}.someProp` and",
        f"// `{name}.onSomeSignal:` all resolve here.",
        f"class {name}Consumer : public SynQt::ConsumerBase",
        "{",
        "    Q_OBJECT",
        f"    QML_ATTACHED({name}Consumer)",
        "    Q_PROPERTY(bool ready READ isReady NOTIFY readyChanged)",
    ]
    for prop in contract.props:
        ctype = cpp_type(prop.type, records, path=path, line=prop.line, col=prop.col)
        lines.append(
            f"    Q_PROPERTY({ctype} {prop.name} READ {prop.name} NOTIFY {prop.name}Changed)")
    for model in contract.models:
        lines.append(
            f"    Q_PROPERTY(QAbstractItemModel *{model.name} READ {model.name} "
            f"NOTIFY {model.name}Changed)")
    lines += [
        "",
        "public:",
        f"    explicit {name}Consumer(QObject *parent = nullptr);",
        "",
        "    QString contractName() const override;",
        "",
        "    // The live facade the runtime installed, not a new object.",
        f"    static {name}Consumer *qmlAttachedProperties(QObject *object);",
        "",
    ]
    for prop in contract.props:
        ctype = cpp_type(prop.type, records, path=path, line=prop.line, col=prop.col)
        lines.append(f"    {ctype} {prop.name}() const;")
    for model in contract.models:
        lines.append(f"    QAbstractItemModel *{model.name}() const;")
    if contract.props or contract.models:
        lines.append("")
    for slot in contract.slots:
        params = _param_list(slot.params, records, path)
        if slot.return_type is None:
            lines.append(f"    Q_INVOKABLE void {slot.name}({params});")
        else:
            lines.append(f"    Q_INVOKABLE SynQt::Promise *{slot.name}({params});")
    if contract.slots:
        lines.append("")
    lines.append("signals:")
    for prop in contract.props:
        lines.append(f"    void {prop.name}Changed();")
    for model in contract.models:
        lines.append(f"    void {model.name}Changed();")
    for signal in contract.signals:
        params = _param_list(signal.params, records, path)
        lines.append(f"    void {signal.name}({params});")
    lines += [
        "",
        "protected:",
        "    void bindReplica() override;",
        "    void emitAllChanged() override;",
    ]
    if contract.models:
        lines += [
            "",
            "private:",
            "    // Each published model reaches a consumer as a read-only view of the Replica's",
            "    // model (SynQt::ReadOnlyModel).",
        ]
        for model in contract.models:
            lines.append(f"    SynQt::ReadOnlyModel *m_{model.name}View{{nullptr}};")
    lines.append("};")
    return "\n".join(lines)


CONSUMER_RELAY_HELPER = """namespace {
// Relay one signal to another by signature, connecting only when both exist (a dynamic
// Replica has no model-changed signal). Returns the connection so the facade can drop
// it on rebind.
QMetaObject::Connection synqtRelay(QObject *from, const QByteArray &fromSignal,
                                   QObject *to, const QByteArray &toSignal)
{
    const QMetaObject *fromMeta{from->metaObject()};
    const QMetaObject *toMeta{to->metaObject()};
    const int fromIndex{fromMeta->indexOfSignal(
        QMetaObject::normalizedSignature(fromSignal.constData()).constData())};
    const int toIndex{toMeta->indexOfSignal(
        QMetaObject::normalizedSignature(toSignal.constData()).constData())};
    if (fromIndex < 0 || toIndex < 0) {
        return QMetaObject::Connection{};
    }
    return QObject::connect(from, fromMeta->method(fromIndex), to, toMeta->method(toIndex));
}
} // namespace
"""


def emit_consumer_source(syn: SynFile, lstem: str) -> str:
    out: List[str] = [SPDX_CPP, f'#include "{lstem}_consumer.h"', "", "#if __has_include(<consumerbase.h>)"]
    # moduleimports.h ships with consumerbase.h, so no second guard.
    out += ['#  include "actingfor.h"',
            '#  include "connectpointresolver.h"',
            '#  include "consumerfactory.h"',
            '#  include "moduleimports.h"', "",
            "#  include <QJSEngine>",
            "#  include <QMetaMethod>",
            "#  include <QMetaObject>",
            "#  include <QtQml/qqmlengine.h>",
            "#  include <QtRemoteObjects/QRemoteObjectPendingReply>",
            "#  include <QVariant>", ""]
    # Only when a facade relays something. A contract of slots alone relays nothing, and an
    # unused function fails the warnings-as-errors build.
    if any(contract.props or contract.models or contract.signals
           for contract in syn.contracts):
        out.append(CONSUMER_RELAY_HELPER)
    records = syn.record_names
    path = f"{syn.stem}.syn"
    for contract in syn.contracts:
        out.append(_consumer_impl(syn, contract, records, path))
        out.append("")
    out.append(f"void synqtRegister{_cap(syn.stem)}Consumers()")
    out.append("{")
    out.append("    // Registering a contract is what makes `import SynQt` enough: it brings")
    out.append("    // QtQuick with it, so a view that consumes this one is a window without a")
    out.append("    // second import line.")
    out.append("    SynQt::registerModuleImports();")
    for contract in syn.contracts:
        out.append(
            f'    SynQt::registerConsumerFactory(QStringLiteral("{contract.name}"),')
        out.append(
            f"        []() -> SynQt::ConsumerBase * {{ return new {contract.name}Consumer{{}}; }});")
        out.append(
            f'    qmlRegisterType<{contract.name}Consumer>("SynQt", 1, 0, '
            f'"{contract.name}");')
    out.append("}")
    out.append("#else")
    out.append(f"void synqtRegister{_cap(syn.stem)}Consumers() {{}}")
    out.append("#endif")
    out.append("")
    return "\n".join(out)


def _consumer_impl(syn: SynFile, contract: Contract, records, path) -> str:
    name = contract.name
    cls = f"{name}Consumer"
    built = "".join(
        f"\n    m_{model.name}View = new SynQt::ReadOnlyModel{{this}};"
        for model in contract.models)
    lines: List[str] = [
        f"{cls}::{cls}(QObject *parent)",
        f"    : SynQt::ConsumerBase{{parent}}",
        "{" + built,
        "}",
        "",
        f"QString {cls}::contractName() const",
        "{",
        f'    return QStringLiteral("{name}");',
        "}",
        "",
        f"{cls} *{cls}::qmlAttachedProperties(QObject *object)",
        "{",
        "    Q_UNUSED(object);",
        f'    QObject *facade{{SynQt::ConnectPointResolver::instance()->resolve('
        f'QStringLiteral("{name}"))}};',
        "    // Owned by the runtime and shared by every file that names it, so the engine must",
        "    // not own it.",
        "    QQmlEngine::setObjectOwnership(facade, QQmlEngine::CppOwnership);",
        f"    return qobject_cast<{cls} *>(facade);",
        "}",
        "",
    ]

    for prop in contract.props:
        ctype = cpp_type(prop.type, records, path=path, line=prop.line, col=prop.col)
        lines += [
            f"{ctype} {cls}::{prop.name}() const",
            "{",
            "    if (!isReady()) {",
            f"        return {ctype}{{}};",
            "    }",
            f'    return qvariant_cast<{ctype}>(m_replica->property("{prop.name}"));',
            "}",
            "",
        ]

    for model in contract.models:
        lines += [
            f"QAbstractItemModel *{cls}::{model.name}() const",
            "{",
            "    if (!isReady()) {",
            "        return nullptr;",
            "    }",
            "    QAbstractItemModel *published{qobject_cast<QAbstractItemModel *>(",
            '        qvariant_cast<QObject *>(m_replica->property("' + model.name + '")))};',
            "    if (published == nullptr) {",
            "        return nullptr;",
            "    }",
            "    // Re-sourced, not rebuilt, so bindings survive a reconnect.",
            "    if (m_" + model.name + "View->sourceModel() != published) {",
            "        m_" + model.name + "View->setSourceModel(published);",
            "    }",
            "    return m_" + model.name + "View;",
            "}",
            "",
        ]

    for slot in contract.slots:
        lines.append(_consumer_slot_impl(syn, name, slot, records, path))
        lines.append("")

    # bindReplica: (re)wire the property, model and signal relays from the Replica.
    lines += [f"void {cls}::bindReplica()", "{"]
    for prop in contract.props:
        ctype = cpp_type(prop.type, records, path=path, line=prop.line, col=prop.col)
        lines.append(
            f'    addConnection(synqtRelay(m_replica, "{prop.name}Changed({ctype})",')
        lines.append(
            f'                             this, "{prop.name}Changed()"));')
    for model in contract.models:
        lines.append(
            f'    addConnection(synqtRelay(m_replica,'
            f' "{model.name}Changed(QAbstractItemModelReplica*)",')
        lines.append(
            f'                             this, "{model.name}Changed()"));')
    for signal in contract.signals:
        types = _types_csv(signal.params, records, path)
        lines.append(
            f'    addConnection(synqtRelay(m_replica, "{signal.name}({types})",')
        lines.append(
            f'                             this, "{signal.name}({types})"));')
    if not (contract.props or contract.models or contract.signals):
        lines.append("    // No push properties, models or signals to relay.")
    lines += ["}", ""]

    lines += [f"void {cls}::emitAllChanged()", "{"]
    for prop in contract.props:
        lines.append(f"    emit {prop.name}Changed();")
    for model in contract.models:
        lines.append(f"    emit {model.name}Changed();")
    if not (contract.props or contract.models):
        lines.append("    // No push properties or models to re-notify.")
    lines.append("}")
    return "\n".join(lines)


def _consumer_slot_impl(syn: SynFile, class_name: str, slot: Slot, records, path) -> str:
    cls = f"{class_name}Consumer"
    params = _param_list(slot.params, records, path)
    qargs = _qarg_suffix(slot.params, records, path)
    if syn.forwards_session:
        # The session this entity acts for, filled by the framework. Empty in a browser.
        qargs = ", Q_ARG(QVariantMap, SynQt::ActingFor::current())" + qargs
    if slot.return_type is None:
        return "\n".join([
            f"void {cls}::{slot.name}({params})",
            "{",
            "    if (!isReady()) {",
            f'        warnNotSent("{slot.name}");',
            "        return;",
            "    }",
            f'    QMetaObject::invokeMethod(m_replica, "{slot.name}"{qargs});',
            "}",
        ])
    ret = cpp_type(slot.return_type, records, path=path, line=slot.line, col=slot.col)
    unavailable = (f'QStringLiteral("the \'{class_name}\' connect point is not available"), '
                   "synqtEngine, this")
    # A typed Replica declares the slot as returning QRemoteObjectPendingReply<T>, a dynamic
    # one (every mesh link) as returning QRemoteObjectPendingCall, and invokeMethod refuses
    # a return argument of the other type. Both are a QRemoteObjectPendingCall.
    return "\n".join([
        f"SynQt::Promise *{cls}::{slot.name}({params})",
        "{",
        "    QJSEngine *synqtEngine{jsEngine()};",
        "    if (!isReady()) {",
        f'        warnNotSent("{slot.name}");',
        f"        return SynQt::Promise::rejected({unavailable});",
        "    }",
        "    QRemoteObjectPendingCall synqtCall;",
        "    bool synqtInvoked{false};",
        f'    if (returnsPendingCall("{slot.name}")) {{',
        f'        synqtInvoked = QMetaObject::invokeMethod(m_replica, "{slot.name}",',
        f"            Q_RETURN_ARG(QRemoteObjectPendingCall, synqtCall){qargs});",
        "    } else {",
        f"        QRemoteObjectPendingReply<{ret}> synqtReply;",
        f'        synqtInvoked = QMetaObject::invokeMethod(m_replica, "{slot.name}",',
        f"            Q_RETURN_ARG(QRemoteObjectPendingReply<{ret}>, synqtReply){qargs});",
        "        synqtCall = synqtReply;",
        "    }",
        "    if (!synqtInvoked) {",
        f"        return SynQt::Promise::rejected({unavailable});",
        "    }",
        "    return new SynQt::Promise{synqtCall, synqtEngine, this};",
        "}",
    ])


# replica side


def emit_replica_header(syn: SynFile, lstem: str) -> str:
    return "\n".join([SPDX_CPP, "#pragma once", "",
                      f"void synqtRegister{_cap(syn.stem)}Replicas();", ""])


def emit_replica_source(syn: SynFile, lstem: str) -> str:
    out = [SPDX_CPP,
           f'#include "{lstem}_replica.h"', "",
           f'#include "{lstem}_rep.h"', "",
           "#include <QQmlEngine>", "",
           "// With the SynQt client runtime linked, register a typed-Replica factory. A",
           "// compile-time Replica carries its API, so it syncs in the browser too, where a",
           "// dynamic Replica's definition exchange does not complete under single-threaded",
           "// WASM. A replica-only target without the runtime skips this.",
           "#if __has_include(<replicaregistry.h>)",
           "#  include <QRemoteObjectNode>",
           "#  include <replicaregistry.h>",
           "#  define SYNQT_REPLICA_FACTORY 1",
           "#endif", "",
           f"void synqtRegister{_cap(syn.stem)}Replicas()",
           "{"]
    for contract in syn.contracts:
        out.append(
            f'    qmlRegisterUncreatableType<{contract.name}Replica>("SynQt", 1, 0,'
        )
        out.append(
            f'        "{contract.name}Replica",'
        )
        out.append(
            f'        QStringLiteral("{contract.name}Replica is acquired from the SynQt '
            'runtime, not constructed in QML"));'
        )
        out.append("#ifdef SYNQT_REPLICA_FACTORY")
        out.append(
            f'    SynQt::registerReplicaFactory(QStringLiteral("{contract.name}"),'
        )
        out.append(
            "        [](QRemoteObjectNode *node, const QString &connectPoint)"
            " -> QRemoteObjectReplica * {"
        )
        out.append(
            f"            return node->acquire<{contract.name}Replica>(connectPoint);"
        )
        out.append("        });")
        out.append("#endif")
    out.append("}")
    out.append("")
    return "\n".join(out)
