// SPDX-FileCopyrightText: 2026 Alexandre 'kidev' Poumaroux
// SPDX-License-Identifier: Apache-2.0

import SynQt

// The authoritative identity Source on the auth entity, one instance per consuming edge.
// It bridges the connect point to the shared IdentityService (the `IdentityEngine` context
// object), which owns the client secret, the token exchange and the stored tokens. Results
// are emitted on this Source, so an identity reaches only the edge that asked. An answer
// that waits on the provider is delivered through this Source when it arrives.
//
// Generated by `synqt build` from `identity.provider_entity`. Edit the topology, not this
// file.
Identity {
    id: root

    function beginLogin(requestId, provider, redirectUri, binding, context) {
        const result = IdentityEngine.beginLogin(provider, redirectUri, binding, context);
        root.emitBeginResult(requestId, result.state, result.authorizeUrl, result.error);
    }

    // The browser binding of this login is stored with the state and checked here before
    // the code is spent, so any edge process can finish a login another began, and only
    // once.
    //
    // The engine answers asynchronously through this Source and the request id, so a slow
    // provider never blocks other callers.
    function exchangeCode(requestId, state, code, redirectUri, presentedBinding) {
        IdentityEngine.exchangeCode(state, code, redirectUri, presentedBinding,
                                    root, requestId);
    }

    function bindSession(state, sessionId) {
        IdentityEngine.bindSession(state, sessionId);
    }

    // A desktop claim is minted on the edge that answered the callback and redeemed over
    // the native client's own connection, possibly on another edge, so it is held here.
    // An empty sessionId means failure, whatever the cause.
    function holdClaim(code, sessionId, challenge) {
        IdentityEngine.holdClaim(code, sessionId, challenge);
    }

    function takeClaim(requestId, code, verifier) {
        root.emitClaimResult(requestId, IdentityEngine.takeClaim(code, verifier));
    }

    function releaseSession(sessionId) {
        IdentityEngine.releaseSession(sessionId);
    }
}
