// SPDX-FileCopyrightText: 2026 Alexandre 'kidev' Poumaroux
// SPDX-License-Identifier: Apache-2.0

import SynQt

// The authoritative session Source on the auth entity, one instance per consuming edge.
// It bridges the connect point to the shared SessionManager (the `Sessions` context
// object): edge writes go into the store, and store changes go to every edge. A newly
// connected edge receives the current table.
//
// Generated by `synqt build` from `identity.provider_entity`. Edit the topology, not this
// file.
SessionStore {
    id: root

    function putSession(token, scope, identityJson, createdMs) {
        Sessions.applyUpsert(token, scope, identityJson, createdMs);
    }

    function removeSession(token) {
        Sessions.applyRemove(token);
    }

    // A session rotation on one edge, carried to every other, since the next page load
    // may land on any edge.
    function rotateSession(from, to) {
        Sessions.applyRotation(from, to);
    }

    function onUpserted(token, scope, identityJson, createdMs) {
        root.emitSessionUpserted(token, scope, identityJson, createdMs);
    }

    function onRemoved(token) {
        root.emitSessionRemoved(token);
    }

    function onRotated(from, to) {
        root.emitSessionRotated(from, to);
    }

    // `root` is the receiver, so the connections go when this Source does. An unshared
    // auth entity has one Source per edge, and an edge that reconnects gets a new one.
    Component.onCompleted: {
        Sessions.sessionUpserted.connect(root, onUpserted);
        Sessions.sessionRemoved.connect(root, onRemoved);
        Sessions.rotationRecorded.connect(root, onRotated);
        const rows = Sessions.snapshot();
        for (let i = 0; i < rows.length; ++i) {
            const row = rows[i];
            root.emitSessionUpserted(row.token, row.scope, row.identityJson, row.createdMs);
        }
    }
}
