#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Alexandre 'kidev' Poumaroux
# SPDX-License-Identifier: Apache-2.0

"""Write the design editor's examples from the projects under `examples/`.

`/designer/#example=<key>` opens one; the document is read with the same code `synqt design`
uses. Run after changing an example or how a project is read:

    python tools/gen-design-examples.py

`tools/synqt/tests/test_designpage.py` fails when the committed file and the projects
disagree. The canvas arrangement lives here, not in the projects.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "tools" / "synqt"))

from synqt import designdoc  # noqa: E402  (after the path is set up)

OUT = Path("tools/synqt/synqt/assets/design/examples.json")

#: Each example: its `#example=<key>`, the project it is read from, its display name, and
#: the canvas position of each entity. `demo` is the key the front page links.
EXAMPLES = {
    "demo": {
        "project": "chat",
        "title": "The chat room",
        "note": "A room, a sign-in, and two gates that are not written in the client.",
        "places": {"app": (64, 160), "edge": (384, 160), "store": (704, 160)},
    },
    "gavel": {
        "project": "gavel",
        "title": "The auction",
        "note": "Signing in, a rule the owner enforces, a permanent Hall of Fame.",
        "places": {"app": (64, 160), "edge": (384, 160), "books": (704, 160)},
    },
    "arena": {
        "project": "arena",
        "title": "The multiplayer arena",
        "note": "A world the edge simulates, and only the slice each player can see.",
        "places": {"app": (64, 160), "edge": (384, 160), "records": (704, 160)},
    },
    "plaza": {
        "project": "plaza",
        "title": "The 3D plaza",
        "note": "People walking in Qt Quick 3D, and an edge that decides where they stand.",
        "places": {"app": (64, 160), "edge": (384, 160)},
    },
    "stall": {
        "project": "stall",
        "title": "The light storefront",
        "note": "Pages the edge delivers, so a campaign changes with no rebuild.",
        "places": {"app": (64, 160), "edge": (384, 160), "stock": (704, 160)},
    },
}

_COMMENT = [
    "GENERATED by tools/gen-design-examples.py. Do not edit.",
    "",
    "Projects the editor can open cold, named in the fragment: /designer/#example=demo.",
    "Each one is read out of the example project of the same name under examples/ by the",
    "same code `synqt design` reads a project on disk with, so what a link hands somebody",
    "and what the tutorial builds cannot part company. They are ordinary design documents",
    "once loaded: edited, checked and exported exactly like something drawn by hand.",
    "",
    "`demo` is the chat room the front page of synqt.org reads out file by file, so the",
    "diagram there and the canvas here are the same system. The other four are what the",
    "tutorials build, and each of those pages links here.",
]


def document(name: str, spec: dict) -> dict:
    """One example, as the design document the editor loads."""
    read = designdoc.read(ROOT / "examples" / spec["project"])
    for entity in read.get("entities", []):
        place = spec["places"].get(entity.get("name"))
        if place is None:
            raise SystemExit(
                f"{name}: '{entity.get('name')}' has no place in EXAMPLES; add one")
        entity["x"], entity["y"] = place
    # Not part of the drawing: `id` and the source digest.
    read.pop("source", None)
    read.pop("digest", None)
    return read


def rendered() -> str:
    payload = {
        "_comment": _COMMENT,
        "about": {name: {"title": spec["title"], "note": spec["note"]}
                  for name, spec in EXAMPLES.items()},
        "examples": {name: document(name, spec) for name, spec in EXAMPLES.items()},
    }
    return json.dumps(payload, indent=1, ensure_ascii=True) + "\n"


def main() -> int:
    path = ROOT / OUT
    text = rendered()
    if path.exists() and path.read_text(encoding="utf-8") == text:
        print(f"unchanged  {OUT}")
        return 0
    path.write_text(text, encoding="utf-8")
    print(f"written    {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
