#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Alexandre 'kidev' Poumaroux
# SPDX-License-Identifier: Apache-2.0

"""Write the design editor's generated assets from the modules that own them: what `synqt add
entity --type monitor` writes (the console client, the sign-in page, the bundle map). Run
after changing what `synqt/monitorscaffold.py` publishes:

    python tools/gen-design-assets.py

`tools/synqt/tests/test_monitoring.py` fails when the committed file and the module
disagree.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "tools" / "synqt"))

from synqt import monitorscaffold  # noqa: E402  (after the path is set up)

#: Every generated asset: its output path, the name the editor imports, and the function
#: that produces it.
ASSETS = {
    Path("tools/synqt/synqt/assets/design/monitor.js"):
        ("MONITOR_SCAFFOLD", monitorscaffold.design_asset),
}

#: An ES module the editor imports, so it is loaded before any editor code runs.
_TEMPLATE = """// SPDX-FileCopyrightText: 2026 Alexandre 'kidev' Poumaroux
// SPDX-License-Identifier: Apache-2.0

// GENERATED by tools/gen-design-assets.py. Do not edit.
//
// What `synqt add entity --type monitor` writes, published so the editor can write the
// same thing with no SynQt behind the page. The scaffolder is the one writer. This is its
// answer, and tools/synqt/tests/test_monitoring.py fails when the two disagree.

export const {name} = {payload};
"""


def rendered(name: str, payload: dict) -> str:
    """The bytes the file holds, so the writer and the drift check agree on formatting."""
    return _TEMPLATE.format(
        name=name, payload=json.dumps(payload, indent=4, sort_keys=True, ensure_ascii=True))


def main() -> int:
    for relative, (name, answer) in ASSETS.items():
        path = ROOT / relative
        text = rendered(name, answer())
        if path.exists() and path.read_text(encoding="utf-8") == text:
            print(f"unchanged  {relative}")
            continue
        path.write_text(text, encoding="utf-8")
        print(f"written    {relative}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
