#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Alexandre 'kidev' Poumaroux
# SPDX-License-Identifier: Apache-2.0

"""Write SynQt's loading page over a bare Qt WebAssembly build directory.

The raw WebAssembly spikes under `tests/` use this instead of Qt's stock page. The markup
and CSS come from `synqt.clientshell.render_client_shell`, the renderer `synqt build` uses.
The boot is the same qtloader call without the manifest fetch and the service worker, which
a spike build does not have.

    tools/wasm-shell.py --target m0-client --out build/m0-client
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

_ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(_ROOT / "synqt"))

from synqt import clientshell  # noqa: E402  (after the path is set up)

# Mirrors clientshell's _BOOT_JS (ids, qtLoad options, overlay), minus the manifest fetch
# (the total comes from Content-Length) and the service worker.
_SPIKE_BOOT_JS = """// SPDX-FileCopyrightText: 2026 Alexandre 'kidev' Poumaroux
// SPDX-License-Identifier: Apache-2.0

// Boots the Qt WebAssembly module for a raw SynQt test spike. External and eval-free,
// like the product boot, so a page served through the edge's Content-Security-Policy
// behaves the same here. Generated by tools/wasm-shell.py. Never edit in place.
(function () {
    "use strict";

    var loading = null;
    var bar = null;
    var status = null;
    var screen = null;

    function setProgress(loaded, total) {
        if (!bar || !(total > 0)) {
            return;
        }
        var percent = Math.max(0, Math.min(100, (loaded / total) * 100));
        bar.style.width = percent.toFixed(1) + "%";
        if (status) {
            status.textContent = "Loading " + percent.toFixed(0) + "%";
        }
    }

    // The chunks go straight through to compileStreaming, so counting them costs no
    // buffering and compilation still overlaps the download.
    function countingResponse(response, total) {
        if (!response.body || typeof TransformStream === "undefined") {
            return response;
        }
        var loaded = 0;
        var counter = new TransformStream({
            transform: function (chunk, controller) {
                loaded += chunk.byteLength;
                setProgress(loaded, total);
                controller.enqueue(chunk);
            }
        });
        return new Response(response.body.pipeThrough(counter), {
            headers: { "Content-Type": "application/wasm" }
        });
    }

    function compileModule() {
        return fetch("TARGET.wasm", { credentials: "same-origin" }).then(function (response) {
            if (!response.ok) {
                throw new Error("could not fetch TARGET.wasm: " + response.status);
            }
            var total = Number(response.headers.get("Content-Length") || 0);
            return WebAssembly.compileStreaming(countingResponse(response, total));
        });
    }

    function fail(error) {
        if (status) {
            status.textContent = "Failed to load";
        }
        if (loading) {
            loading.hidden = false;
        }
        console.error(error);
    }

    function init() {
        loading = document.querySelector("#synqt-loading");
        bar = document.querySelector("#synqt-bar");
        status = document.querySelector("#synqt-status");
        screen = document.querySelector("#screen");

        try {
            qtLoad({
                qt: {
                    module: compileModule(),
                    onLoaded: function () {
                        if (loading) {
                            loading.hidden = true;
                        }
                    },
                    onExit: function (exitData) {
                        var suffix = exitData.code !== undefined
                            ? " with code " + exitData.code : "";
                        if (status) {
                            status.textContent = "Application exit" + suffix;
                        }
                        if (loading) {
                            loading.hidden = false;
                        }
                    },
                    entryFunction: window.ENTRY_FUNCTION,
                    containerElements: [screen]
                }
            });
        } catch (error) {
            fail(error);
        }
    }

    window.addEventListener("load", init);
})();
"""


def render(target: str, out_dir: Path) -> None:
    """Write index.html and synqt-boot.js for `target` into `out_dir`."""
    # An empty config: every `build.loading` value takes its default.
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "index.html").write_text(
        clientshell.render_client_shell("%s.js" % target, {}, out_dir), encoding="utf-8")
    # Emscripten turns dashes in the target name into underscores for the entry symbol.
    entry = "%s_entry" % target.replace("-", "_")
    (out_dir / "synqt-boot.js").write_text(
        _SPIKE_BOOT_JS.replace("TARGET", target).replace("ENTRY_FUNCTION", entry),
        encoding="utf-8")


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--target", required=True,
                        help="The CMake target name of the WebAssembly client.")
    parser.add_argument("--out", required=True,
                        help="The build directory holding <target>.js and qtloader.js.")
    arguments = parser.parse_args(argv)

    out_dir = Path(arguments.out)
    if not (out_dir / ("%s.js" % arguments.target)).exists():
        print("wasm-shell: %s/%s.js is missing; build the client first"
              % (out_dir, arguments.target), file=sys.stderr)
        return 1
    render(arguments.target, out_dir)
    return 0


if __name__ == "__main__":
    sys.exit(main())
